const $=s=>document.querySelector(s),esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const modules=COURSE.modules;let slides=[],currentPage=1,routeToken=0;
const dataReady=fetch('slides.json').then(r=>{if(!r.ok)throw Error('课件内容暂时无法加载');return r.json()}).then(d=>slides=d);dataReady.catch(()=>{});

const topicEnrichment={
workflow:{goals:['把个人需求拆成可执行步骤','识别适合自动化与必须人工核验的环节'],activity:'任选一个重复性任务，写出输入、处理、输出和检查点。',question:'如果流程能够稳定运行，是否说明结果已经可靠？',answer:'还不能。稳定运行只说明程序没有中断。数据是否完整、筛选规则是否合理、输出是否准确，仍需分别检查。'},
crawl:{goals:['区分网页获取、正文提取与结构化输出','理解数据来源和字段检查的重要性'],activity:'选择一个网页，列出真正需要保留的三个字段，并说明每个字段的用途。',question:'为什么抓到完整 HTML 仍不等于获得了可用数据？',answer:'网页还包含导航、广告、重复文本和动态内容。下游任务需要结构清楚、字段稳定且保留来源的数据。'},
homepage:{goals:['理解仓库、网页内容与 GitHub Pages 的关系','能够规划学术主页的信息层级'],activity:'用一分钟浏览三个主页案例，记录最先看到的信息和最容易找到的入口。',question:'学术主页首页应该优先放完整履历，还是研究方向与代表成果？',answer:'通常先呈现研究身份、方向和代表成果，再提供完整履历入口。具体顺序取决于网站主要服务的读者。'},
ai:{goals:['区分人工智能、机器学习与深度学习','理解行为测试与系统能力之间的差别'],activity:'为“空间推理能力”设计一个只靠套话难以通过的小测试。',question:'语言回答像人，能否证明系统具备通用智能？',answer:'不能。语言表现只能覆盖部分能力，空间感知、规划、行动和持续学习还需要专门任务验证。'},
vlm:{goals:['按输入、输出和训练目标比较三类视觉语言模型','根据任务选择模型能力'],activity:'分别为图文检索、遥感图像生成和图像问答选择一种模型架构，并说明理由。',question:'模型参数更多，是否一定更适合当前任务？',answer:'不一定。任务形式、训练数据、评价指标和部署成本都会影响选择。模型规模只是其中一个因素。'},
remote:{goals:['从对象识别扩展到位置与空间关系','理解地理定位任务的尺度和计算难点'],activity:'观察一幅遥感图，依次回答“有什么、在哪里、与周围对象有什么关系”。',question:'为什么有限地图上的 Geo-Localization 难以直接推广到全球？',answer:'全球影像规模更大，地貌重复、季节和视角变化更强，检索范围和计算成本也显著增加。'},
tasks:{goals:['区分 Caption、VQA 与 Grounding 的输出','判断答案是否具有空间证据'],activity:'把一句图像描述改写为一个视觉问答问题，再改写为一个需要定位目标的指令。',question:'一个模型回答正确，为什么仍可能不具备可靠的空间理解？',answer:'模型可能利用语言先验或数据偏差得到答案。Grounding 要求它同时指出图像证据，能更直接地检验空间对应关系。'},
airspatial:{goals:['理解二维定位与三维空间感知的差别','认识几何信息对细粒度属性识别的作用'],activity:'列出无人机从二维图像估计车辆三维位置所需的相机或飞行信息。',question:'为什么三维尺寸能够帮助识别细粒度车辆型号？',answer:'不同车型在长宽高和比例上存在差异。把视觉外观与几何尺寸结合，可以减少只凭颜色或纹理造成的混淆。'},
dvg:{goals:['理解隐式需求到显式视觉条件的转换','识别推理链中可能出现的错误'],activity:'把“找到最需要救援的车辆”拆成可观察的图像条件。',question:'隐式指令最容易在哪个环节出错？',answer:'系统可能先误解任务意图，也可能推断出错误的视觉条件。即使条件正确，最后的目标定位仍可能失败。'},
datasets:{goals:['比较人工、自动与半自动构造数据集的取舍','理解质量验证比样本数量更基础'],activity:'为一个新的无人机问答数据集设计两条人工抽检规则。',question:'自动生成十万条样本，为什么仍可能不如小规模人工数据？',answer:'自动流程可能系统性地产生错误、重复和捷径。高质量数据还需要明确任务定义、覆盖目标场景并验证标注。'},
flight:{goals:['理解主动感知中的行动与观察闭环','区分静态识别和持续状态估计'],activity:'为“扫描一栋被遮挡的建筑”设计下一观察位置的选择依据。',question:'无人机为什么需要主动改变视角？',answer:'新的视角可以减少遮挡和不确定性，补充固定图像无法提供的信息，并帮助系统更新环境模型。'},
action:{goals:['理解语言指令如何转化为可执行动作','认识动力学、安全约束与反馈的作用'],activity:'把“抓取红色物体”补充成一条包含目标、路径与安全条件的执行说明。',question:'图像问答模型为什么不能直接替代无人机控制系统？',answer:'控制系统需要连续估计状态、规划动作并满足动力学和安全约束，还要根据实时反馈调整。'},
worldmodel:{goals:['理解世界模型对未来状态的预测作用','认识仿真到现实迁移的价值和限制'],activity:'区分像素重建和表示空间预测各自关注的信息。',question:'世界模型预测准确，是否就能保证无人机安全？',answer:'不能。控制策略、传感器误差、动力学差异和未见环境都会影响安全，仍需闭环验证和保护机制。'}
};

const specialGuides={
1:['课程全景','本讲从 AI 工具实践出发，逐步进入遥感多模态模型、空间推理和无人机行动。先建立全局路线，再进入具体方法。','四个模块之间如何从“处理信息”过渡到“在物理世界行动”？','工具实践提供数据与流程基础；多模态模型连接视觉和语言；空间任务加入位置证据；具身系统再把感知结果转化为行动。'],
2:['教师与课程背景','这一页帮助你了解课程视角：遥感图像智能解译、低空空间感知与无人机具身智能共同构成本讲的研究背景。','教师的研究经历会如何影响课程案例的选择？','课程更关注遥感多模态模型、三维空间感知和低空行动，因此案例集中在这些方向。'],
3:['学习路线图','教师把自己的角色比作“导游”：本讲提供领域地图和研究入口，帮助你判断每条路线通往什么问题，再选择值得深入的方向。','导论课更应该覆盖所有细节，还是建立问题地图？','导论课首先要建立概念关系和问题地图。细节可以在后续课程、论文和实验中深入。'],
15:['结构化结果','这一页展示抓取后的 CSV。阅读时检查每一行是否对应一个视频，以及 aid、标题、发布时间等字段能否支持后续筛选。','哪些字段用于唯一标识，哪些字段用于排序或筛选？','aid 适合唯一标识视频；标题和发布时间可用于关键词、时间范围筛选；统计字段可用于评分。'],
18:['排序与人工清洗','程序按 score 降序得到候选榜单，随后删除搬运、教程和非本人演奏等不符合目标的投稿。自动评分与人工审核共同决定最终结果。','为什么不把所有筛选规则都写进程序？','部分规则依赖语境和内容判断，难以仅凭结构化字段准确识别。人工复核可以处理边界情况。'],
50:['主页案例观察一','观察首屏如何回答三个问题：作者是谁、研究什么、希望访问者接下来查看什么。先看信息顺序，再看配色。','你能在十秒内找到作者的研究方向吗？','如果可以，说明首屏层级清楚；如果需要反复滚动，导航和内容顺序仍可改进。'],
51:['主页案例观察二','比较个人介绍、论文列表和项目入口的篇幅。优秀主页会根据目标读者安排重点，而不是平均分配空间。','面向招生与面向同行的主页，内容排序应有什么差别？','面向招生时可突出研究方向、团队机会和联系方式；面向同行时可优先呈现论文、代码和项目。'],
52:['主页案例观察三','把这个案例当作信息架构练习：记录最先看到的内容、最容易点击的入口，以及一项可以删减的信息。','主页内容越多是否越专业？','不是。内容应服务读者任务。过多信息会稀释重点，维护成本也更高。'],
67:['视觉语言模型的任务版图','课件列出二十类能力。更稳妥的整理方式是先看输入和输出，再把计数、测量和属性识别等问题归入 Caption、VQA、Grounding 或分割等基本任务。','为什么按论文名称不断增加任务类别会失去控制？','同一能力可能使用不同名称，新论文也会持续创造细分任务。按输入、输出和证据形式组织更稳定。'],
68:['Geo-Localization','目标是用无人机图像在离线卫星地图中找到对应位置。有限虚拟地图可以验证方法，但全球尺度会带来重复地貌、视角变化和大规模检索问题。','从游戏地图扩大到真实世界，首要瓶颈是什么？','需要同时解决数据覆盖、跨视角匹配、检索规模和真实环境变化，很难归结为单一瓶颈。'],
69:['补充视频','观看时记录视频中的任务输入、空间证据和输出形式，并与上一页 Geo-Localization 的问题设定比较。','视频中的系统依靠了哪些空间信息？','可从位置、尺度、视角、对象关系和地图先验等方面记录，具体以视频内容为准。'],
81:['研究增长的证据','图表用于观察数据集与论文数量的变化。阅读趋势图时先确认横轴时间、统计口径和数据来源，再讨论增长原因。','数量增长能否直接说明研究质量提高？','不能。数量只反映活跃度，还要结合任务难度、数据质量、可复现性和真实应用效果。'],
82:['大模型与专用模型','专用模型通常在固定任务上更高效；大模型的价值在于用统一接口处理多种任务，减少重复开发和维护。选择时要同时看效果与系统成本。','固定场景中仍应优先使用大模型吗？','不一定。若任务稳定、资源受限且评价明确，专用模型可能更合适。需要多任务交互和开放指令时，大模型更有优势。'],
83:['科研问题的变化','大模型让研究从为固定任务设计网络，转向定义新的任务、数据和系统。空间智能需要把模型、工具、知识、仿真和验证组织起来。','新的模型能力为什么会改变研究问题本身？','统一的多模态接口降低了跨任务试验成本，使研究者可以提出过去缺少方法支持的三维理解和自主行动问题。'],
84:['AirSpatialBot 的研究问题','这一页把二维视觉定位扩展到三维空间。数据采集同时记录无人机、相机与地面目标信息，再用摄影测量建立空间对应。','如果只保留图像而丢失相机参数，会损失什么？','系统难以把像素位置可靠地转换为真实空间位置，也无法建立可验证的三维标注。'],
99:['位置提示与二轮质询','实验显示，裁剪后的第二轮查询和位置提示能够找回第一轮未检测到的车辆。这里应关注额外上下文如何改变模型判断。','二轮查询为什么可能提高召回率？','裁剪区域减少了背景干扰，位置提示又为模型提供了更明确的空间线索。'],
104:['课程回顾','回看本讲的主线：数据和工具支撑模型，视觉语言任务加入空间证据，主动系统再把理解转化为行动。','你会选择哪一个环节继续深入？','可以从数据、模型、空间任务或无人机系统中选择一个方向，并用本讲的案例作为论文检索起点。'],
105:['课程结语视频','观看结语时用三句话记录：本讲最重要的概念、最想继续研究的问题，以及一个可以动手验证的小实验。','如何把一门导论课转化为下一步行动？','选择一个明确问题，阅读一篇代表论文，复现一个最小实验，再根据结果调整问题。']
};

function moduleForPage(p){return modules.find(m=>p>=m.start&&p<=m.end)||modules[0]}
function guideForSlide(s,p){const x=specialGuides[p];if(x)return{label:x[0],reading:x[1],question:x[2],answer:x[3]};const title=s.text?.[0]||'图示阅读';if(p>=5&&p<=23)return{label:'自动化工作流',reading:`把“${title}”放回完整流程中理解：它接收什么输入，产生什么输出，下一步如何使用这个结果。`,question:'这一环节最需要检查的数据或规则是什么？',answer:'先检查输入是否完整，再检查处理规则是否符合目标，最后抽样核对输出。'};if(p>=24&&p<=27)return{label:'网页信息采集',reading:'这一组页面把网页内容转成适合模型和表格处理的数据。重点观察页面获取、内容提取和结构化输出的边界。',question:'如果网页结构变化，流程中哪个环节最先受到影响？',answer:'页面定位和内容提取通常最先受影响，因此需要保留样本测试和字段完整性检查。'};if(p>=28&&p<=52)return{label:'学术主页实践',reading:`这一页对应主页建设中的“${title}”。先判断当前操作的目标，再观察它改变了仓库、配置还是页面内容。`,question:'完成这一步后，怎样确认修改已经正确发布？',answer:'检查仓库中的文件变化、GitHub Pages 构建状态和公开页面，必要时刷新缓存并核对链接。'};if(p>=54&&p<=62)return{label:'人工智能基础',reading:`围绕“${title}”区分概念定义、可观察行为与真正需要验证的能力。`,question:'这页内容描述的是模型方法、行为表现，还是能力假设？',answer:'先看它是否给出算法机制、测试中的回答，或对理解与推理能力的判断。三者需要不同证据。'};if(p>=63&&p<=71)return{label:'视觉语言模型',reading:`阅读“${title}”时，先找出输入、输出和训练目标，再判断示例解决的是匹配、生成、问答还是定位。`,question:'这个任务需要模型给出答案，还是同时给出空间证据？',answer:'Caption 和 VQA 可以只输出文字；Grounding 和分割还要给出位置或像素证据。'};if(p>=72&&p<=91)return{label:'任务与空间推理',reading:`这页用“${title}”说明任务或数据如何扩展。比较前后变化时，关注输入范围、输出粒度和证据形式。`,question:'新任务增加的难点来自数据、推理还是评价？',answer:'通常三者都会变化。可分别检查标注是否可获得、模型需要哪些中间推理，以及评价能否验证空间对应。'};if(p>=92&&p<=105)return{label:'物理世界中的空间智能',reading:`把“${title}”放在感知、规划、行动和反馈的闭环中理解，判断这一页主要解决哪个环节。`,question:'这一能力如何在真实环境中接受验证？',answer:'需要在闭环任务中检查状态估计、动作执行、反馈更新与安全约束，单张图片上的结果不足以证明系统可用。'};return{label:'本页导读',reading:'先辨认页面主题，再用图示和文字建立它与前后页面的关系。',question:'这一页在整讲课程中承担什么作用？',answer:'可以从引入问题、解释方法、展示证据或总结结论四类作用中判断。'}}

$('#module-nav').innerHTML=modules.map(m=>`<div class="nav-module"><a href="#read/${m.id}" data-module="${m.id}"><span class="num">${m.no}</span><span>${m.title}</span></a><small>课件 ${m.range} 页</small></div>`).join('');
$('#menu').addEventListener('click',()=>{const o=$('#sidebar').classList.toggle('open');$('#menu').setAttribute('aria-expanded',String(o))});
function figure(page,cls=''){const fs=slides[page-1]?.figures||[],f=fs.find(x=>!x.animated)||fs[0];if(!f)return'';return`<figure class="${cls}"><img src="${f.poster||f.src}" alt="课件第 ${page} 页图示" loading="lazy" data-zoom><figcaption><span>课程图示 · 第 ${page} 页</span><span>点击图示可放大</span></figcaption></figure>`}
function toc(items){return`<aside class="page-toc"><p>本页内容</p>${items.map(([id,t])=>`<a href="#${id}">${t}</a>`).join('')}<div class="toc-note"><p>授课教师</p><strong>周越</strong><br>华东师范大学<br><br>第一讲 · 105 页课程演示<br>阅读、讨论与逐页演示</div></aside>`}
function home(){return`<div class="page-grid"><div><section><div class="eyebrow">华东师范大学 · 第一讲</div><h1>空间人工智能<em>导论</em></h1><p class="english">Introduction to Spatial Artificial Intelligence</p><p class="intro">遥感多模态大模型，迈向真实的物理世界。<br>从图像与语言的理解出发，探索空间感知、视觉推理与无人机行动。</p><div class="actions"><a class="button primary" href="#read">开始阅读 <span>→</span></a><a class="button" href="#slides/1">▣ &nbsp;逐页浏览</a><a class="button" href="#print">导出 PDF</a></div><div class="metadata"><span><strong>01</strong> 讲课程</span><span><strong>04</strong> 个主题模块</span><span><strong>105</strong> 页课程演示</span></div>${figure(84,'hero-figure')}</section><section class="section" id="about"><div class="section-heading"><h2>关于这门课</h2><span>ABOUT THIS COURSE</span></div><p>模型如何从识别一张图像，走向理解空间关系并在物理世界中行动？这门导论课结合 AI 工具实践、遥感视觉语言模型与无人机研究案例，建立从数据、任务到感知和行动的知识脉络。</p><div class="note"><strong>一份课程，三种使用方式</strong><p>连续讲义用于理解概念；逐页浏览将 PPT 重组为自学页面并加入导读与讨论；打印版适合保存为 PDF 或离线阅读。</p></div></section><section class="section" id="syllabus"><div class="section-heading"><h2>课程内容</h2><span>COURSE CONTENTS</span></div>${modules.map(m=>`<a class="module-card" href="#read/${m.id}"><span class="module-no">${m.no}</span><div><h3>${m.title}</h3><p>${m.desc}</p><span class="module-pages">课程演示 ${m.range} 页 · ${m.topics.length} 个主题</span></div><span class="module-arrow">↗</span></a>`).join('')}</section><section class="section" id="teacher"><div class="section-heading"><h2>授课教师</h2><span>INSTRUCTOR</span></div><div class="teacher"><div class="teacher-mark">周</div><div><strong>周越</strong><p>华东师范大学 · 副教授</p><p><a href="mailto:yzhou@geoai.ecnu.edu.cn">yzhou@geoai.ecnu.edu.cn</a></p><p><a href="https://zhouyue.space" target="_blank" rel="noopener">个人主页 ↗</a></p></div></div></section></div>${toc([['overview','课程概览'],['about','关于这门课'],['syllabus','课程内容'],['teacher','授课教师']])}</div>`}
function enrichmentHTML(t,print=false){const x=topicEnrichment[t.id];if(!x)return'';return`<div class="topic-enrichment"><div><span class="mini-label">自学目标</span><ul>${x.goals.map(g=>`<li>${g}</li>`).join('')}</ul></div><div><span class="mini-label">动手练习</span><p>${x.activity}</p></div></div><details class="discussion" ${print?'open':''}><summary><span>讨论</span>${x.question}<small>展开参考答案</small></summary><p>${x.answer}</p></details>`}
function topicHTML(t){return`<article class="topic" id="${t.id}"><div class="topic-heading"><h3>${t.title}</h3><a href="#slides/${t.start}">课程演示 ${t.pages} 页 ↗</a></div>${t.body}${t.figure?figure(t.figure):''}${enrichmentHTML(t)}${t.question?`<details><summary><div class="question-label">复习思考 · 网页补充</div>${t.question}</summary><p>${t.answer}</p></details>`:''}</article>`}
function reading(selected){const chosen=selected?modules.filter(m=>m.id===selected):modules,ms=chosen.length?chosen:modules;return`<div class="page-grid"><div><div class="reading-header"><div class="eyebrow">LECTURE 01 · 课程讲义</div><h1>${selected&&chosen.length?chosen[0].title:'空间人工智能导论'}</h1><p class="intro">${selected&&chosen.length?chosen[0].desc:'从 AI 工具实践到物理世界中的空间智能。按主题阅读，完成自学目标、练习和讨论。'}</p><div class="actions"><a class="button primary" href="#slides/${ms[0].start}">逐页浏览本模块 →</a>${selected?'<a class="button" href="#read">连续阅读全讲</a>':''}<a class="button" href="#print">导出 PDF</a></div></div>${ms.map(m=>`<section><div class="module-title" id="module-${m.id}"><small>MODULE ${m.no} · ${m.en}</small><h2>${m.title}</h2><p>课程演示 ${m.range} 页</p></div>${m.topics.map(topicHTML).join('')}</section>`).join('')}</div>${toc(ms.flatMap(m=>m.topics.map(t=>[`topic/${t.id}`,t.title])))}</div>`}
function glossary(){return`<div class="eyebrow">GLOSSARY</div><h1>术语索引</h1><p class="intro">课程中的核心概念，及其对应的讲义主题。</p><div class="glossary-grid">${COURSE.glossary.map(([en,cn,d,id])=>`<article class="term"><strong>${en}</strong><h3>${cn}</h3><p>${d}</p><a href="#topic/${id}">回到讲义 →</a></article>`).join('')}</div>`}
function resources(){const cases=[['GRAFT','CLIP-based 遥感视觉语言模型 · 课件标注 ICLR 2024',64],['DiffusionSat','Diffusion-based 遥感生成模型 · 课件标注 ICLR 2024',65],['GeoChat','遥感多模态指令与问答 · 课件标注 CVPR 2024',66],['AirSpatialBot','无人机空间感知、车辆属性识别与检索 · 课件标注 IEEE TGRS 2025',84],['DVGBench','无人机影像中的隐式到显式视觉定位 · 课件标注 ISPRS JPRS 2026',86],['XLRS-Bench / VRSBench','数据集构造案例 · 课件标注 CVPR 2025 / NeurIPS 2024',89],['FlyCo','开放世界环境中的无人机自主三维结构扫描',95],['UAV Claw','无人机听指令行动',97],['Hand-like autonomous flying robot','空中抓取与交互',98],['SkyJEPA','长时程世界模型与零样本仿真到现实控制',99]];return`<div class="eyebrow">SOURCES & FURTHER READING</div><h1>来源与参考资料</h1><p class="intro">课程内容依据周越《空间人工智能导论》103 页 PPT 整理；网页另加入 2 页视频内容，共 105 页课程演示。</p><div class="note"><strong>课件与网页内容</strong><p>网页对原课件文字、图示与演讲注释进行了自学化重组，并补充阅读提示、讨论和练习。行业信息与论文标注沿用课件制作时的内容。</p></div><h2>课件中的研究案例</h2><ul class="resources-list">${cases.map(([a,b,p])=>`<li><strong>${a}</strong><p>${b}</p><a href="#slides/${p}">查看课程演示 · 第 ${p} 页 →</a></li>`).join('')}</ul><section class="section"><h2>网站结构参考</h2><p><a class="button" href="https://github.com/Visionary-Laboratory/parallel-computing-course" target="_blank" rel="noopener">并行计算与算子编程 · 公开课程网站 ↗</a></p><p>参考其课程概览、连续讲义、逐页演示、讨论与打印版的组织方式。本网站代码和课程内容独立实现。</p></section>`}
function mediaHTML(s,p){const fs=s.figures||[];if(s.embed?.provider==='bilibili')return`<div class="slide-embed"><div class="video-frame"><iframe src="https://player.bilibili.com/player.html?bvid=${encodeURIComponent(s.embed.bvid)}&page=1&high_quality=1&danmaku=0&autoplay=0" title="${esc(s.embed.title||'课程视频')}" loading="lazy" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share; fullscreen" allowfullscreen referrerpolicy="strict-origin-when-cross-origin"></iframe></div><p><a class="button" href="${esc(s.embed.url)}" target="_blank" rel="noopener noreferrer">在哔哩哔哩打开 ↗</a></p></div>`;if(!fs.length)return'<div class="concept-stage"><span>SPATIAL AI</span><strong>概念与章节过渡</strong><p>结合导读理解本页在整讲课程中的位置。</p></div>';return`<div class="slide-media ${fs.length===1?'single':fs.length>3?'gallery':''}">${fs.map((f,i)=>`<figure><img src="${f.poster||f.src}" alt="第 ${p} 页图示 ${i+1}" loading="lazy" data-zoom>${f.animated?`<button class="animation-button" data-animation="${f.src}" data-video="${f.video?1:0}" data-poster="${f.poster}" aria-pressed="false">播放动画</button>`:''}<figcaption>图 ${i+1} · 点击放大${f.animated?' / 可播放动画':''}</figcaption></figure>`).join('')}</div>`}
function presentation(page){const total=slides.length;currentPage=Math.min(total,Math.max(1,parseInt(page)||1));const s=slides[currentPage-1];if(!s)return'<div class="error">课件尚未加载。</div>';const raw=s.text||[],title=raw[0]||`图示阅读 · 第 ${currentPage} 页`,points=raw.slice(1).filter(t=>t.trim()).slice(0,6),remaining=raw.slice(7).filter(t=>t.trim()),g=guideForSlide(s,currentPage),m=moduleForPage(currentPage),links=s.links||[];return`<section class="slide-app" id="slide-app"><div class="slide-toolbar"><select id="page-select" aria-label="选择课件页码">${slides.map(x=>`<option value="${x.page}" ${x.page===currentPage?'selected':''}>${String(x.page).padStart(3,'0')} · ${esc((x.text[0]||'图示阅读').slice(0,48))}</option>`).join('')}</select><div class="controls"><a class="button" href="#read/${m.id}">返回讲义</a><a class="button" href="#print">导出 PDF</a><button class="button" id="fullscreen">全屏 F</button></div></div><article class="slide-sheet"><div class="slide-label"><span>MODULE ${m.no} · ${esc(m.title)}</span><span>${String(currentPage).padStart(3,'0')} / ${total}</span></div><div class="slide-heading"><span>${g.label}</span><h1>${esc(title)}</h1><p>${g.reading}</p></div><div class="slide-composition"><div class="visual-column">${mediaHTML(s,currentPage)}</div><aside class="study-column">${points.length?`<div class="key-points"><span class="mini-label">课件要点</span><ul>${points.map(t=>`<li>${esc(t)}</li>`).join('')}</ul>${remaining.length?`<details class="raw-copy"><summary>展开其余课件文字</summary>${remaining.map(t=>`<p>${esc(t)}</p>`).join('')}</details>`:''}</div>`:`<div class="reading-cue"><span class="mini-label">自主阅读</span><p>先观察图中的对象、箭头、标注与对比关系，再用上方导读解释这张图支持了什么观点。</p></div>`}<details class="discussion"><summary><span>讨论</span>${g.question}<small>展开参考答案</small></summary><p>${g.answer}</p></details></aside></div>${links.filter(l=>/^https?:\/\//i.test(l)).map((l,i)=>`<p><a class="button" href="${esc(l)}" target="_blank" rel="noopener">课件外部链接 ${i+1} ↗</a></p>`).join('')}</article><div class="slide-progress"><span style="width:${currentPage/total*100}%"></span></div><div class="slide-footer"><button id="prev" class="button" ${currentPage===1?'disabled':''}>← 上一页</button><span>第 ${currentPage} 页 / 共 ${total} 页</span><button id="next" class="button primary" ${currentPage===total?'disabled':''}>下一页 →</button></div><p class="help">← / → 翻页 · F 全屏 · 点击图示放大 · 讨论答案默认折叠</p></section>`}
function printView(){return`<article class="print-course"><div class="print-controls"><div><div class="eyebrow">PRINT EDITION</div><h1>空间人工智能导论</h1><p>打印版包含课程讲义、自学目标、练习、讨论与参考答案。点击按钮后，在浏览器打印窗口中选择“另存为 PDF”。</p></div><button class="button primary" id="print-course">打印 / 另存为 PDF</button></div><header class="print-cover"><p>华东师范大学 · 第一讲</p><h1>空间人工智能导论</h1><h2>Introduction to Spatial Artificial Intelligence</h2><p>周越</p></header><section class="print-outline"><h2>课程目录</h2>${modules.map(m=>`<p><strong>${m.no} ${m.title}</strong><span>${m.range} 页</span></p>`).join('')}</section>${modules.map(m=>`<section class="print-module"><div class="module-title"><small>MODULE ${m.no} · ${m.en}</small><h2>${m.title}</h2><p>${m.desc}</p></div>${m.topics.map(t=>`<article class="topic"><h3>${t.title}</h3>${t.body}${t.figure?figure(t.figure):''}${enrichmentHTML(t,true)}${t.question?`<div class="print-question"><strong>复习思考</strong><p>${t.question}</p><p><b>参考答案：</b>${t.answer}</p></div>`:''}</article>`).join('')}</section>`).join('')}<section class="print-end"><h2>课程结束</h2><p>网页课程演示共 ${slides.length} 页，其中包含 3 个 Bilibili 视频页。视频请在在线课程网站中观看。</p></section></article>`}
function bind(){document.querySelectorAll('[data-zoom]').forEach(img=>{img.tabIndex=0;img.setAttribute('role','button');img.setAttribute('aria-label',img.alt+'，点击放大');const open=()=>{$('#lightbox img').src=img.src;$('#lightbox img').alt=img.alt;$('#lightbox p').textContent=img.alt;$('#lightbox').showModal()};img.onclick=open;img.onkeydown=e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();open()}}});document.querySelectorAll('[data-animation]').forEach(b=>b.onclick=()=>{const playing=b.getAttribute('aria-pressed')==='true';if(b.dataset.video==='1'){let v=b.parentElement.querySelector('video');if(!v){v=document.createElement('video');v.src=b.dataset.animation;v.poster=b.dataset.poster;v.controls=true;v.loop=true;v.muted=true;v.playsInline=true;b.previousElementSibling.hidden=true;b.before(v)}if(playing)v.pause();else v.play().catch(()=>b.textContent='请点击视频播放按钮')}else b.previousElementSibling.src=playing?b.dataset.poster:b.dataset.animation;b.setAttribute('aria-pressed',String(!playing));b.textContent=playing?'播放动画':'暂停动画'});if($('#page-select')){$('#page-select').onchange=e=>location.hash=`slides/${e.target.value}`;$('#prev').onclick=()=>navigateSlide(-1);$('#next').onclick=()=>navigateSlide(1);$('#fullscreen').onclick=toggleFullscreen}if($('#print-course'))$('#print-course').onclick=()=>window.print()}
function navigateSlide(d){const p=currentPage+d;if(p>=1&&p<=slides.length)location.hash=`slides/${p}`}
async function toggleFullscreen(){try{if(document.fullscreenElement)await document.exitFullscreen();else await $('#main').requestFullscreen()}catch{alert('此浏览器暂不支持全屏，请使用浏览器的全屏功能。')}}
async function render(){const token=++routeToken,[view,sub]=(location.hash.slice(1)||'overview').split('/');try{await dataReady}catch(e){if(token===routeToken)$('#main').innerHTML=`<div class="error">${esc(e.message)}。请刷新页面重试。</div>`;return}if(token!==routeToken)return;let content,label,active=view;if(view==='slides'){content=presentation(sub);label='逐页浏览';active='read'}else if(view==='glossary'){content=glossary();label='术语索引'}else if(view==='resources'){content=resources();label='来源与参考资料'}else if(view==='print'){content=printView();label='打印与导出 PDF'}else if(view==='read'||view==='topic'){const m=view==='topic'?modules.find(m=>m.topics.some(t=>t.id===sub)):null;content=reading(m?.id||(view==='read'?sub:null));label=m?.title||modules.find(m=>m.id===sub)?.title||'连续讲义';active='read'}else{content=home();label='课程概览';active='overview'}$('#main').innerHTML=content;$('#crumb').textContent=`课程讲义 / ${label}`;document.title=`${label} · 空间人工智能导论`;document.querySelectorAll('[data-nav]').forEach(a=>a.classList.toggle('active',a.dataset.nav===active));document.querySelectorAll('[data-module]').forEach(a=>a.classList.toggle('active',a.dataset.module===sub));$('#sidebar').classList.remove('open');$('#menu').setAttribute('aria-expanded','false');bind();if(document.fullscreenElement)document.fullscreenElement.scrollTop=0;else window.scrollTo({top:0,behavior:'instant'});const target=view==='topic'?sub:['about','syllabus','teacher'].includes(view)?view:null;if(target)document.getElementById(target)?.scrollIntoView({behavior:'instant'})}
$('#close-image').onclick=()=>$('#lightbox').close();$('#lightbox').onclick=e=>{if(e.target===$('#lightbox'))$('#lightbox').close()};document.addEventListener('keydown',e=>{if($('#lightbox').open||/INPUT|SELECT|TEXTAREA/.test(e.target.tagName))return;if(location.hash.startsWith('#slides/')){if(e.key==='ArrowRight'){e.preventDefault();navigateSlide(1)}if(e.key==='ArrowLeft'){e.preventDefault();navigateSlide(-1)}if(e.key.toLowerCase()==='f'){e.preventDefault();toggleFullscreen()}}if(e.key==='Escape'){$('#sidebar').classList.remove('open');$('#menu').setAttribute('aria-expanded','false')}});$('.skip').onclick=e=>{e.preventDefault();$('#main').focus();$('#main').scrollIntoView()};window.addEventListener('hashchange',render);render();
