const $=s=>document.querySelector(s), esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const modules=COURSE.modules; let slides=[], currentPage=1, routeToken=0;
const dataReady=fetch('slides.json').then(r=>{if(!r.ok)throw Error('课件内容暂时无法加载');return r.json()}).then(d=>slides=d);
dataReady.catch(()=>{});
$('#module-nav').innerHTML=modules.map(m=>`<div class="nav-module"><a href="#read/${m.id}" data-module="${m.id}"><span class="num">${m.no}</span><span>${m.title}</span></a><small>课件 ${m.range} 页</small></div>`).join('');
$('#menu').addEventListener('click',()=>{const open=$('#sidebar').classList.toggle('open');$('#menu').setAttribute('aria-expanded',String(open))});
function figure(page,cls=''){const fs=slides[page-1]?.figures||[];const f=fs.find(x=>!x.animated)||fs[0];if(!f)return '';return `<figure class="${cls}"><img src="${f.poster||f.src}" alt="课件第 ${page} 页图示" loading="lazy" data-zoom><figcaption><span>课件图示 · 第 ${page} 页</span><span>点击图示可放大</span></figcaption></figure>`}
function toc(items){return `<aside class="page-toc"><p>本页内容</p>${items.map(([id,t])=>`<a href="#${id}">${t}</a>`).join('')}<div class="toc-note"><p>授课教师</p><strong>周越</strong><br>华东师范大学<br><br>第一讲 · 103 页课件<br>阅读与逐页演示</div></aside>`}
function home(){return `<div class="page-grid"><div><section><div class="eyebrow">华东师范大学 · 第一讲</div><h1>空间人工智能<em>导论</em></h1><p class="english">Introduction to Spatial Artificial Intelligence</p><p class="intro">遥感多模态大模型，迈向真实的物理世界。<br>从图像与语言的理解出发，探索空间感知、视觉推理与无人机行动。</p><div class="actions"><a class="button primary" href="#read">开始阅读 <span>→</span></a><a class="button" href="#slides/1">▣ &nbsp;逐页浏览</a></div><div class="metadata"><span><strong>01</strong> 讲课程</span><span><strong>04</strong> 个主题模块</span><span><strong>103</strong> 页原课件内容</span></div>${figure(83,'hero-figure')}</section><section class="section" id="about"><div class="section-heading"><h2>关于这门课</h2><span>ABOUT THIS COURSE</span></div><p>模型如何从识别一张图像，走向理解空间关系并在物理世界中行动？这门导论课结合 AI 工具实践、遥感视觉语言模型与无人机研究案例，建立从数据、任务到感知和行动的知识脉络。</p><div class="note"><strong>一份课程，两种阅读方式</strong><p>连续讲义帮助梳理概念和案例；逐页浏览保留 PPT 的全部页码、文字与图示，并针对网页重新排版。动画可按需播放。</p></div></section><section class="section" id="syllabus"><div class="section-heading"><h2>课程内容</h2><span>COURSE CONTENTS</span></div>${modules.map(m=>`<a class="module-card" href="#read/${m.id}"><span class="module-no">${m.no}</span><div><h3>${m.title}</h3><p>${m.desc}</p><span class="module-pages">课件 ${m.range} 页 · ${m.topics.length} 个主题</span></div><span class="module-arrow">↗</span></a>`).join('')}</section><section class="section" id="teacher"><div class="section-heading"><h2>授课教师</h2><span>INSTRUCTOR</span></div><div class="teacher"><div class="teacher-mark">周</div><div><strong>周越</strong><p>华东师范大学 · 副教授</p><p><a href="mailto:yzhou@geoai.ecnu.edu.cn">yzhou@geoai.ecnu.edu.cn</a></p><p><a href="https://zhouyue.space" target="_blank" rel="noopener">个人主页 ↗</a></p></div></div></section><section class="section"><div class="section-heading"><h2>学习资源</h2><span>LEARNING RESOURCES</span></div><div class="actions"><a class="button" href="#glossary">术语索引 →</a><a class="button" href="#resources">课件来源与参考资料 →</a></div></section></div>${toc([['overview','课程概览'],['about','关于这门课'],['syllabus','课程内容'],['teacher','授课教师'],['resources','参考资料']])}</div>`}
function topicHTML(t){return `<article class="topic" id="${t.id}"><div class="topic-heading"><h3>${t.title}</h3><a href="#slides/${t.start}">课件 ${t.pages} 页 ↗</a></div>${t.body}${t.figure?figure(t.figure):''}${t.question?`<details><summary><div class="question-label">复习思考 · 网页补充</div>${t.question}</summary><p>${t.answer}</p></details>`:''}</article>`}
function reading(selected){const chosen=selected?modules.filter(m=>m.id===selected):modules;const ms=chosen.length?chosen:modules;return `<div class="page-grid"><div><div class="reading-header"><div class="eyebrow">LECTURE 01 · 课程讲义</div><h1>${selected&&chosen.length?chosen[0].title:'空间人工智能导论'}</h1><p class="intro">${selected&&chosen.length?chosen[0].desc:'从 AI 工具实践到物理世界中的空间智能。按主题阅读，或跳转到对应课件。'}</p><div class="actions"><a class="button primary" href="#slides/${ms[0].start}">逐页浏览本模块 →</a>${selected?'<a class="button" href="#read">连续阅读全讲</a>':''}</div></div>${ms.map(m=>`<section><div class="module-title" id="module-${m.id}"><small>MODULE ${m.no} · ${m.en}</small><h2>${m.title}</h2><p>课件 ${m.range} 页</p></div>${m.topics.map(topicHTML).join('')}</section>`).join('')}<div class="note"><strong>继续学习</strong><p><a href="#glossary">查阅术语索引 →</a> &nbsp; <a href="#resources">查看来源与参考资料 →</a></p></div></div>${toc(ms.flatMap(m=>m.topics.map(t=>[`topic/${t.id}`,t.title])))}</div>`}
function glossary(){return `<div class="eyebrow">GLOSSARY</div><h1>术语索引</h1><p class="intro">课程中的核心概念，及其对应的讲义主题。</p><div class="glossary-grid">${COURSE.glossary.map(([en,cn,desc,id])=>`<article class="term"><strong>${en}</strong><h3>${cn}</h3><p>${desc}</p><a href="#topic/${id}">回到讲义 →</a></article>`).join('')}</div>`}
function resources(){return `<div class="eyebrow">SOURCES & FURTHER READING</div><h1>来源与参考资料</h1><p class="intro">课程内容依据周越《空间人工智能导论》PPT 整理，共 103 页。</p><div class="note"><strong>课件与网页内容</strong><p>逐页浏览呈现课件原有文字与图示，不包含演讲者备注；网页重新组织版式，不复刻 PowerPoint 的动画转场。连续讲义、术语释义和复习问题为教学整理与补充，可结合原课件页码核对。</p></div><h2>课件中的研究案例</h2><ul class="resources-list">${[['GRAFT','CLIP-based 遥感视觉语言模型 · 课件标注 ICLR 2024',64],['DiffusionSat','Diffusion-based 遥感生成模型 · 课件标注 ICLR 2024',65],['GeoChat','遥感多模态指令与问答 · 课件标注 CVPR 2024',66],['AirSpatialBot','无人机空间感知、车辆属性识别与检索 · 课件标注 IEEE TGRS 2025',83],['DVGBench','无人机影像中的隐式到显式视觉定位 · 课件标注 ISPRS JPRS 2026',85],['XLRS-Bench / VRSBench','数据集构造案例 · 课件标注 CVPR 2025 / NeurIPS 2024',88],['FlyCo','开放世界环境中的无人机自主三维结构扫描',94],['UAV Claw','无人机听指令行动',96],['Hand-like autonomous flying robot','空中抓取与交互',97],['SkyJEPA','长时程世界模型与零样本仿真到现实控制',98]].map(([a,b,p])=>`<li><strong>${a}</strong><p>${b}</p><a href="#slides/${p}">查看课件与原图 · 第 ${p} 页 →</a></li>`).join('')}</ul><section class="section"><h2>网站结构参考</h2><p><a class="button" href="https://github.com/Visionary-Laboratory/parallel-computing-course" target="_blank" rel="noopener">并行计算与算子编程 · 公开课程网站 ↗</a></p><p>参考其课程概览、连续讲义、逐页演示与术语索引的组织方式。本网站代码独立实现。</p></section><p class="citation">课件及第三方图像、论文与动画的权利归各自作者或权利人。以上文献信息沿用课件标注，不代表实时更新的文献或产业数据。</p>`}
function presentation(page){currentPage=Math.min(103,Math.max(1,parseInt(page)||1));const s=slides[currentPage-1];if(!s)return '<div class="error">课件尚未加载。</div>';const txt=s.text||[];let title=txt[0]||`课件图示 · 第 ${currentPage} 页`;const body=txt.slice(1);return `<section class="slide-app" id="slide-app"><div class="slide-toolbar"><select id="page-select" aria-label="选择课件页码">${slides.map(x=>`<option value="${x.page}" ${x.page===currentPage?'selected':''}>${String(x.page).padStart(3,'0')} · ${esc((x.text[0]||'课件图示').slice(0,48))}</option>`).join('')}</select><div class="controls"><a class="button" href="#read/${modules.find(m=>currentPage>=m.start&&currentPage<=m.end)?.id||'practice'}">返回讲义</a><button class="button" id="fullscreen">全屏 F</button></div></div><div class="slide-sheet"><div class="slide-label"><span>空间人工智能导论 · 课件内容 / 网页重排</span><span>${String(currentPage).padStart(3,'0')} / 103</span></div><h1>${esc(title)}</h1><div class="slide-text">${body.map(t=>`<p>${esc(t)}</p>`).join('')}</div><div class="slide-media ${s.figures.length===1?'single':''}">${s.figures.map((f,i)=>`<figure><img src="${f.poster||f.src}" alt="第 ${currentPage} 页图示 ${i+1}" loading="lazy" data-zoom>${f.animated?`<button class="animation-button" data-animation="${f.src}" data-video="${f.video?1:0}" data-poster="${f.poster}" aria-pressed="false">播放动画</button>`:''}<figcaption>课件第 ${currentPage} 页 · 图 ${i+1}</figcaption></figure>`).join('')}</div>${s.links.filter(x=>/^https?:\/\//i.test(x)).map((l,i)=>`<p><a class="button" href="${esc(l)}" target="_blank" rel="noopener">课件外部链接 ${i+1} ↗</a></p>`).join('')}</div><div class="slide-progress"><span style="width:${currentPage/103*100}%"></span></div><div class="slide-footer"><button id="prev" class="button" ${currentPage===1?'disabled':''}>← 上一页</button><span>第 ${currentPage} 页 / 共 103 页</span><button id="next" class="button primary" ${currentPage===103?'disabled':''}>下一页 →</button></div><p class="help">← / → 翻页 · F 全屏 · 点击图示放大 · 动画按需播放</p></section>`}
function bind(){document.querySelectorAll('[data-zoom]').forEach(img=>{img.tabIndex=0;img.setAttribute('role','button');img.setAttribute('aria-label',img.alt+'，点击放大');const open=()=>{$('#lightbox img').src=img.src;$('#lightbox img').alt=img.alt;$('#lightbox p').textContent=img.alt;$('#lightbox').showModal()};img.onclick=open;img.onkeydown=e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();open()}}});document.querySelectorAll('[data-animation]').forEach(b=>b.onclick=()=>{const playing=b.getAttribute('aria-pressed')==='true';if(b.dataset.video==='1'){let video=b.parentElement.querySelector('video');if(!video){video=document.createElement('video');video.src=b.dataset.animation;video.poster=b.dataset.poster;video.controls=true;video.loop=true;video.muted=true;video.playsInline=true;video.setAttribute('aria-label','课件动画');b.previousElementSibling.hidden=true;b.before(video)}if(playing){video.pause()}else{video.play().catch(()=>{b.textContent='请点击视频播放按钮'})}}else{b.previousElementSibling.src=playing?b.dataset.poster:b.dataset.animation}b.setAttribute('aria-pressed',String(!playing));b.textContent=playing?'播放动画':'暂停动画'});if($('#page-select')){$('#page-select').onchange=e=>location.hash=`slides/${e.target.value}`;$('#prev').onclick=()=>navigateSlide(-1);$('#next').onclick=()=>navigateSlide(1);$('#fullscreen').onclick=toggleFullscreen}}
function navigateSlide(d){const p=currentPage+d;if(p>=1&&p<=103)location.hash=`slides/${p}`}
async function toggleFullscreen(){try{if(document.fullscreenElement)await document.exitFullscreen();else await $('#main').requestFullscreen()}catch{alert('此浏览器暂不支持全屏，请使用浏览器的全屏功能。')}}
async function render(){const token=++routeToken;let path=(location.hash.slice(1)||'overview').split('/');const [view,sub]=path;try{await dataReady}catch(e){if(token===routeToken)$('#main').innerHTML=`<div class="error">${esc(e.message)}。请刷新页面重试。</div>`;return}if(token!==routeToken)return;let content,label,active=view;
 if(view==='slides'){content=presentation(sub);label='逐页浏览';active='read'}else if(view==='glossary'){content=glossary();label='术语索引'}else if(view==='resources'){content=resources();label='来源与参考资料'}else if(view==='read'||view==='topic'){const m=view==='topic'?modules.find(m=>m.topics.some(t=>t.id===sub)):null;content=reading(m?.id||(view==='read'?sub:null));label=m?.title||modules.find(m=>m.id===sub)?.title||'连续讲义';active='read'}else{content=home();label='课程概览';active='overview'}
 $('#main').innerHTML=content;$('#crumb').textContent=`课程讲义 / ${label}`;document.title=`${label} · 空间人工智能导论`;document.querySelectorAll('[data-nav]').forEach(a=>a.classList.toggle('active',a.dataset.nav===active));document.querySelectorAll('[data-module]').forEach(a=>a.classList.toggle('active',a.dataset.module===sub));$('#sidebar').classList.remove('open');$('#menu').setAttribute('aria-expanded','false');bind();
 if(document.fullscreenElement){document.fullscreenElement.scrollTop=0}else window.scrollTo({top:0,behavior:'instant'});
 const target=view==='topic'?sub:['about','syllabus','teacher'].includes(view)?view:null;if(target)document.getElementById(target)?.scrollIntoView({behavior:'instant'});
}
$('#close-image').onclick=()=>$('#lightbox').close();$('#lightbox').onclick=e=>{if(e.target===$('#lightbox'))$('#lightbox').close()};
document.addEventListener('keydown',e=>{if($('#lightbox').open||/INPUT|SELECT|TEXTAREA/.test(e.target.tagName))return;if(location.hash.startsWith('#slides/')){if(e.key==='ArrowRight'){e.preventDefault();navigateSlide(1)}if(e.key==='ArrowLeft'){e.preventDefault();navigateSlide(-1)}if(e.key.toLowerCase()==='f'){e.preventDefault();toggleFullscreen()}}if(e.key==='Escape'){$('#sidebar').classList.remove('open');$('#menu').setAttribute('aria-expanded','false')}});
$('.skip').onclick=e=>{e.preventDefault();$('#main').focus();$('#main').scrollIntoView()};window.addEventListener('hashchange',render);render();
