window.COURSE = {
modules: [
 {id:'practice',no:'00',title:'AI 带来的改变',en:'AI IN PRACTICE',range:'04–52',start:4,end:52,desc:'从兴趣创作、信息采集到学术主页，理解 AI 如何进入真实工作流。',topics:[
  {id:'workflow',title:'从兴趣到自动化工作流',pages:'5–23',start:5,body:`<p>课件从口琴乐谱与 Bilibili 视频创作切入，展示如何把一个个人需求拆分为信息获取、内容处理与结果输出。重点是把问题描述清楚，再将重复步骤组织成可执行的流程。</p><div class="flow"><span><b>01</b>采集视频信息</span><span><b>02</b>计算与筛选</span><span><b>03</b>填充内容模板</span><span><b>04</b>编辑与发布</span></div><p>读这一组案例时，留意每一步的输入和输出：哪些步骤适合程序化处理，哪些结果仍需要人工检查？</p>`,question:'一个自动化流程能运行，是否就意味着结果可靠？',answer:'不意味着。需要分别检查数据是否完整、筛选规则是否符合目的，以及最终输出是否准确。把验证放在关键环节，才能知道错误来自哪里。'},
  {id:'crawl',title:'Crawl4AI 与网页信息采集',pages:'24–27',start:24,body:`<p>网页信息是许多 AI 应用的数据来源。课件以 Crawl4AI 为例，对比传统网页解析与面向 AI 的信息采集流程，讨论如何减少手工编写页面选择器的工作。</p><p>学习时关注三个环节：页面获取、正文提取和结构化输出。获得网页内容之后，还要判断哪些字段与任务相关，哪些信息需要保留来源。</p>`,question:'网页已经抓取成功，为什么还需要检查提取结果？',answer:'获取页面和获得有效数据是两个环节。导航栏、重复内容、动态加载区域以及缺失字段都可能影响下游任务，需要用实际样本检查。'},
  {id:'homepage',title:'构建自己的学术主页',pages:'28–52',start:28,body:`<p>课件以 AcadHomepage 为例，讲解从模板到个人网站的全过程。核心是理解仓库、页面内容和托管服务之间的关系。</p><ol class="steps"><li><strong>Fork 模板仓库</strong>，在自己的账户下获得可维护的副本。</li><li><strong>配置 GitHub Pages</strong>，将仓库内容发布为网站。</li><li><strong>等待构建完成</strong>，检查发布状态与访问地址。</li><li><strong>编辑 <code>_config.yml</code></strong>，更新网站标题和个人资料。</li><li><strong>编辑 <code>_pages/about.md</code></strong>，补充介绍、研究方向与成果。</li></ol><p>课件最后展示多个学术主页案例，可以比较其信息组织方式，再决定自己的主页应优先呈现什么。</p>`}
 ]},
 {id:'foundations',no:'01',title:'人工智能与多模态基础',en:'FOUNDATIONS',range:'53–71',start:53,end:71,desc:'认识人工智能、机器学习和深度学习，比较三类视觉语言模型。',topics:[
  {id:'ai',title:'人工智能、学习与推理',pages:'54–62',start:54,body:`<p>人工智能关注能够完成感知、推理和决策等任务的系统；机器学习通过数据学习规律；深度学习使用多层神经网络学习表示。课件从分类例子出发，介绍图灵测试、弱人工智能与强人工智能，以及符号主义和连接主义。</p><p>围绕“机器是否理解”的课堂讨论，需要区分可观察到的回答与系统实际具备的能力。语言流畅、回答一致或符合人的直觉，都不能单独证明系统具有通用智能。</p><div class="note"><strong>课堂讨论</strong><p>当相同问题被连续提出时，机械重复与结合上下文作答有什么区别？怎样设计新的测试，排除仅凭表面语言判断能力的误差？</p></div>`,question:'图灵测试是否等价于检验所有智能能力？',answer:'不等价。它聚焦交互中的行为表现；空间推理、感知、规划和真实环境中的行动还需要针对性的任务与评价。课件中的简化描述适合作为讨论起点。'},
  {id:'vlm',title:'三类视觉语言模型',pages:'63–66',start:63,figure:63,body:`<p>视觉语言模型将图像与语言联系起来。课件按主要建模方式介绍三类架构，并以遥感研究中的 GRAFT、DiffusionSat 和 GeoChat 为例。</p><div class="table-wrap"><table><thead><tr><th>架构</th><th>主要思路</th><th>课件案例</th></tr></thead><tbody><tr><td>CLIP-based</td><td>将图像与文本映射到可比较的表示空间</td><td>GRAFT</td></tr><tr><td>Diffusion-based</td><td>以文本或其他条件引导图像生成</td><td>DiffusionSat</td></tr><tr><td>LLM / LMM-based</td><td>连接视觉编码器与语言模型，完成问答或指令任务</td><td>GeoChat</td></tr></tbody></table></div><p>比较架构时，先看输入、输出和训练目标，再看模型规模。不同模型解决的问题并不完全相同。</p>`,question:'图文检索与生成一张遥感图像，应关注同一种模型能力吗？',answer:'不应。图文检索关注跨模态表示与匹配；图像生成关注条件控制和生成结果。选择模型应从任务所需的输入、输出与评价标准出发。'},
  {id:'remote',title:'遥感任务与空间信息',pages:'67–71',start:67,body:`<p>课件从模型支持的地物类别延伸到 Geo-Localization，并讨论商业航天与多模态模型的联系。图像中的对象、位置、尺度和相互关系，为空间智能提供了不同层次的信息。</p><p>复习时可以沿着“看到什么、在哪里、与周围对象有什么关系”逐步提问。识别对象类别只是起点，空间理解还涉及位置关系与场景约束。</p><div class="note"><strong>阅读提示</strong><p>课件中的产业新闻和估值属于制作时的背景材料，不作为本课程的实时数据。</p></div>`}
 ]},
 {id:'research',no:'02',title:'任务、数据与空间推理',en:'TASKS & SPATIAL REASONING',range:'72–91',start:72,end:91,desc:'梳理 Caption、VQA 与 Grounding，理解数据集构造和无人机空间感知。',topics:[
  {id:'tasks',title:'遥感多模态任务的演变',pages:'72–83',start:72,body:`<p>课件沿图像描述、视觉问答与视觉定位三条线索，展示任务如何从整幅图像扩展到区域、时间变化与更复杂的指代表达。</p><div class="table-wrap"><table><thead><tr><th>任务</th><th>问题形式</th><th>输出形式</th></tr></thead><tbody><tr><td>Caption</td><td>图像或区域中发生了什么？</td><td>文字描述</td></tr><tr><td>VQA</td><td>针对图像提出一个问题</td><td>答案</td></tr><tr><td>REC / Grounding</td><td>找出语言指代的对象</td><td>目标位置或边界框</td></tr><tr><td>RES</td><td>精确分割语言指代的对象</td><td>像素级掩膜</td></tr></tbody></table></div><p>区域级任务要求关注局部对象；时序任务引入多时相信息；Grounded Caption 与 Grounded VQA 将文字输出和空间证据连接起来。研究问题也由“能否回答”进一步转向“回答能否被图像证据支持”。</p>`,question:'“画面里有一辆车”与“找到桥下等待救援的车辆”有什么差别？',answer:'前者是描述，后者需要根据语言定位目标，并可能推断对象、场景和事件之间的关系。后者不仅要求识别类别，还要求理解指代条件。'},
  {id:'airspatial',title:'AirSpatialBot：无人机空间感知',pages:'84–85',start:84,figure:84,body:`<p>二维识别可以描述目标的颜色和相对大小，但真实场景还需要理解三维位置、距离以及对象之间的空间关系。课件以 AirSpatialBot 为案例，介绍面向无人机影像的空间感知、细粒度车辆属性识别与检索。</p><p>阅读图示时，可将任务分为视觉问答、视觉定位、空间问答与空间定位，观察不同任务需要哪些几何信息。第 85 页进一步展示车辆型号识别案例。</p><p class="citation">课件文献：AirSpatialBot: A Spatially Aware Aerial Agent for Fine-Grained Vehicle Attribute Recognition and Retrieval. IEEE TGRS, 2025.</p>`},
  {id:'dvg',title:'DVGBench：从隐式需求到视觉定位',pages:'86–88',start:86,figure:86,body:`<p>用户的需求不一定直接点出目标名称。课件介绍 DVGBench，将交通管理、灾害救援、公共安全、体育赛事、社交活动和生产活动作为隐式推理场景。</p><p>理解隐式指令，需要先把任务意图转化为可观察的条件，再根据图像证据定位目标。课件以“隐转显”的推理过程说明如何连接语言需求与视觉定位。</p><p class="citation">课件文献：DVGBench: Implicit-to-Explicit Visual Grounding Benchmark in UAV Imagery with Large Vision-Language Models. ISPRS JPRS, 2026.</p>`,question:'为什么隐式指令比直接给出目标名称更难？',answer:'系统需要先理解任务意图，推断对象应具备的视觉或场景条件，再执行定位。任一环节出错，都可能导致最终位置错误。'},
  {id:'datasets',title:'三种数据集构造方式',pages:'89–91',start:89,body:`<div class="table-wrap"><table><thead><tr><th>方式</th><th>分工</th><th>主要取舍</th><th>课件案例</th></tr></thead><tbody><tr><td>完全人工</td><td>专家生成、验证和优化</td><td>控制细致，但人力成本高</td><td>XLRS-Bench</td></tr><tr><td>完全自动</td><td>依据已有数据与规则生成</td><td>易扩展，但需关注规则与多样性</td><td>GeoChat</td></tr><tr><td>半自动</td><td>模型生成，人工验证与优化</td><td>兼顾效率与质量，仍需验证</td><td>VRSBench</td></tr></tbody></table></div><p>这三种方式对应不同的质量、规模与成本要求。设计数据集时，先明确任务与标注标准，再决定自动化程度。自动生成的标签仍需验证生成规则、原始数据与任务假设是否一致。</p>`,question:'构建一个强调复杂推理的新基准，为什么不能只关注样本数量？',answer:'还要检查标注是否可靠、是否覆盖目标场景、是否存在歧义，以及模型能否利用捷径作答。规模无法替代任务定义和质量验证。'}
 ]},
 {id:'physical',no:'03',title:'迈向真实的物理世界',en:'EMBODIED SPATIAL INTELLIGENCE',range:'92–105',start:92,end:105,desc:'从自主飞行到主动感知、指令行动和世界模型，连接理解与控制。',topics:[
  {id:'flight',title:'自主飞行与主动感知',pages:'93–96',start:93,body:`<p>课件展示本科生参与的无人机自主飞行实验，并引入主动感知：无人机通过选择行动或观察位置，获得完成任务所需的信息。</p><p>FlyCo 案例关注开放环境中的自主三维结构扫描；海上主动感知实验则将感知任务放入实际场景。观察演示时，区分飞行平台、观测目标、路径选择与感知结果。</p><div class="flow"><span><b>感知</b>获取环境信息</span><span><b>规划</b>选择下一步动作</span><span><b>行动</b>改变观察位置</span><span><b>反馈</b>更新环境理解</span></div>`,question:'主动感知与在固定视角下分析一张图像有什么区别？',answer:'主动感知把行动作为获取信息的一部分。系统可以改变视角、距离或路径，以减少遮挡和不确定性，而不是只利用已经给定的观测。'},
  {id:'action',title:'听指令行动与空中交互',pages:'97–98',start:97,body:`<p>课件以 UAV Claw 展示语言指令与无人机行动的连接，并以空中抓取机器人展示与物理对象的交互。</p><p>相比静态图像问答，真实行动还涉及时间、动力学和环境反馈。阅读这些案例时，要问清楚语言指令如何转化为目标，感知结果怎样影响动作，以及系统如何判断任务完成。</p><p class="citation">课件案例：UAV Claw；Hand-like autonomous flying robot for airborne grasping and interaction.</p>`},
  {id:'worldmodel',title:'JEPA 与无人机世界模型',pages:'99–103',start:99,figure:99,body:`<p>“看懂”环境与在环境中稳定行动之间仍有距离。课件以 SkyJEPA 为例，讨论长时程世界模型与无人机的零样本仿真到现实控制。</p><p>世界模型尝试建立环境变化的可预测表示，为规划和控制提供依据。JEPA（联合嵌入预测架构）关注在表示空间中的预测，而非必须重建每个像素。</p><p>结合第 99–103 页的框架与结果图，思考表示学习、状态预测和控制策略之间如何衔接。</p><p class="citation">课件文献：SkyJEPA: Learning Long-Horizon World Models for Zero-Shot Sim-to-Real Control of Quadrotors.</p>`,question:'在图像理解任务上表现良好，为什么不一定能直接控制无人机？',answer:'控制需要根据随时间变化的状态产生动作，并满足动力学约束。感知模型的输出还需要与状态估计、规划、控制和反馈环节衔接。'}
 ]}
],
glossary:[
['AI','人工智能','研究感知、推理、学习与决策等能力的系统。','ai'],['ML','机器学习','利用数据学习规律并用于预测或决策的方法。','ai'],['DL','深度学习','通过多层神经网络学习数据表示。','ai'],['VLM','视觉语言模型','联合处理视觉与语言信息的模型。','vlm'],['CLIP','对比语言图像预训练','通过图文对齐学习跨模态表示，可用于匹配与检索。','vlm'],['LLM / LMM','大语言模型 / 大型多模态模型','分别侧重语言建模与多种模态信息的联合处理。','vlm'],['Diffusion','扩散模型','通过逐步去噪等过程进行生成的模型。','vlm'],['LoRA','低秩适配','通过训练低秩参数对大模型进行高效适配的方法。','vlm'],['Caption','图像描述','为整幅图像或局部区域生成文字描述。','tasks'],['VQA','视觉问答','结合视觉内容回答自然语言问题。','tasks'],['Visual Grounding','视觉定位','将语言描述关联到图像中的目标或区域。','tasks'],['REC','指代表达理解','根据语言表达定位目标，通常输出边界框。','tasks'],['RES','指代表达分割','根据语言表达输出目标的像素级掩膜。','tasks'],['Geo-Localization','地理定位','根据观测信息确定对应的地理位置。','remote'],['Active Perception','主动感知','通过选择动作或观察位置获取更有用的信息。','flight'],['JEPA','联合嵌入预测架构','在表示空间中学习预测的架构。','worldmodel'],['World Model','世界模型','用于表示环境及预测环境或状态变化的模型。','worldmodel'],['Sim-to-Real','仿真到现实','将仿真中学习或验证的能力迁移到真实环境。','worldmodel']
]
};
