window.BEGINNER_TERMS = [
  {term:'AI',cn:'人工智能',aliases:['Artificial Intelligence','人工智能'],pages:[1,4,27,55,56,57,58,59,60,61,62,70],plain:'让计算机完成过去通常需要人来完成的感知、理解、推理、生成或决策任务的技术总称。它是一个很大的领域，不等于某一种软件或某一个聊天机器人。',example:'手机识别人脸、地图规划路线、模型回答问题，都是人工智能的不同应用。',note:'AI 是上位概念；机器学习和深度学习是实现 AI 的两类方法。'},
  {term:'机器学习（ML）',cn:'Machine Learning',aliases:['Machine Learning','机器学习'],pages:[54,55,62],plain:'不给计算机逐条写死规则，而是让它从许多样本中找规律，再对新样本作预测。',example:'给模型看很多“芒果”和“苹果”的图片，模型学习后判断一张新图属于哪一类。',note:'机器学习不一定使用神经网络；决策树、支持向量机也属于机器学习。'},
  {term:'深度学习（DL）',cn:'Deep Learning',aliases:['Deep Learning','深度学习'],pages:[54,62],plain:'机器学习的一类方法，使用很多层神经网络逐层提取信息，特别擅长处理图像、语音和文本。',example:'前几层找边缘和纹理，后几层把这些信息组合成车、建筑或道路。',note:'“深”主要指网络层数较多，不表示模型一定像人一样理解问题。'},
  {term:'神经网络',cn:'Neural Network',aliases:['神经网络','神经元'],pages:[54,62],plain:'由大量简单计算单元连接而成的数学模型。训练时会调整连接的数值，使输出逐渐接近正确答案。',example:'输入一张图片，网络经过多层计算，最后输出“车辆”的概率。',note:'它受到大脑连接方式的启发，但不是人脑的完整复制。'},
  {term:'特征',cn:'Feature',aliases:['特征工程','特征'],pages:[54,62,85],plain:'能够帮助模型区分或判断事物的信息。传统方法常由人设计特征，深度学习常从数据中自动学习。',example:'车辆的长宽比、颜色、轮廓和纹理都可以作为特征。',note:'特征是用于计算的信息，不等于对象的全部属性。'},
  {term:'感知机',cn:'Perceptron',aliases:['感知机'],pages:[62],plain:'一种早期的人工神经网络模型，把输入加权求和后作简单判断，是理解神经网络的入门模型。',example:'根据“是否有叶片”和“是否为绿色”等输入，输出是否属于植物。',note:'单层感知机只能解决较简单的线性分类问题。'},
  {term:'反向传播（BP）',cn:'Backpropagation',aliases:['BP'],pages:[62],plain:'训练神经网络的基本算法。它从输出错误出发，反向计算每个参数应如何调整。',example:'模型把苹果认成芒果后，BP 会把错误逐层传回，微调网络参数。',note:'BP 是训练方法；神经网络是被训练的模型结构。'},
  {term:'LeNet',cn:'早期卷积神经网络',aliases:['LeNet'],pages:[62],plain:'用于手写数字识别的经典神经网络，展示了卷积网络如何从图像中逐层提取特征。',example:'识别银行卡或邮政编码中的 0—9 手写数字。',note:'它规模很小，但对后来图像深度学习的发展影响很大。'},
  {term:'DBN',cn:'深度置信网络',aliases:['DBN'],pages:[62],plain:'一种由多层概率模型组成的早期深度学习结构，曾用于逐层预训练深层网络。',example:'先让每一层学习数据结构，再整体微调完成分类。',note:'它是深度学习发展史上的重要方法，目前图像任务更常使用卷积网络或 Transformer。'},
  {term:'GAN',cn:'生成对抗网络',aliases:['GAN'],pages:[62],plain:'让“生成器”和“判别器”相互较量：一个努力造出逼真数据，另一个努力辨别真假。',example:'生成器画人脸，判别器判断是不是训练集中的真实照片。',note:'GAN 与扩散模型都能生成图像，但训练方式不同。'},
  {term:'图灵测试',cn:'Turing Test',aliases:['The Turing Test','图灵测试'],pages:[56,57,58,59,60,61,62],plain:'让人只通过文字交流判断对方是人还是机器，用机器能否表现出类似人的对话行为来讨论智能。',example:'提问者看不到对方，只比较两位回答者的文字回复。',note:'通过测试说明行为像人，不足以证明机器拥有人的意识或所有智能。'},
  {term:'弱人工智能',cn:'Narrow AI',aliases:['弱人工智能'],pages:[61],plain:'在特定任务上表现很好，但能力范围有限的人工智能。今天绝大多数 AI 系统属于这一类。',example:'围棋程序会下棋，却不一定能做饭或理解法律。',note:'“弱”不是性能差，而是适用范围窄。'},
  {term:'强人工智能 / 通用智能',cn:'Strong AI / AGI',aliases:['强人工智能','通用智能'],pages:[61],plain:'设想中能够像人一样跨任务学习、理解、推理并适应新环境的系统。',example:'同一个系统能学习语言、科学、驾驶和家务，并把一种经验迁移到另一种任务。',note:'这是研究目标和讨论概念，不能只凭流畅对话就断定已经实现。'},
  {term:'认知',cn:'Cognition',aliases:['认知'],pages:[61],plain:'获取、组织和使用信息的一系列过程，包括注意、记忆、理解、判断等。',example:'看到路口后识别车辆、记住信号灯并判断能否通行。',note:'模型输出正确，不一定说明它采用了和人相同的认知过程。'},
  {term:'推理',cn:'Reasoning',aliases:['推理','视觉推理'],pages:[61,84,86,87,88],plain:'根据已知信息经过若干逻辑或因果步骤得到新结论。',example:'看到道路积水和停驶车辆，推断哪辆车可能最需要救援。',note:'识别“这是一辆车”主要是感知；根据条件判断“应该找哪辆车”才涉及推理。'},
  {term:'符号主义',cn:'Symbolic AI',aliases:['符号主义','符号表达'],pages:[62],plain:'用清晰的符号、事实和规则表示知识，再按逻辑规则进行推理的 AI 路线。',example:'规则“所有哺乳动物会呼吸；鲸是哺乳动物”，可推出“鲸会呼吸”。',note:'规则容易解释，但面对复杂图像和不完整世界时，手写所有规则很困难。'},
  {term:'专家系统',cn:'Expert System',aliases:['专家系统','规则系统'],pages:[62],plain:'把专家经验写成知识库和规则，让计算机在特定领域给出判断或建议。',example:'根据症状和规则辅助判断设备可能出现的故障。',note:'它依靠显式规则，和从大量数据中学习规律的神经网络不同。'},
  {term:'联结主义',cn:'Connectionism',aliases:['联结主义'],pages:[62],plain:'通过大量相互连接的简单计算单元学习能力的 AI 路线，现代神经网络是其代表。',example:'模型从大量图片中自己学会哪些组合特征对应“汽车”。',note:'它善于从数据学习，但内部计算往往不如规则系统直观。'},
  {term:'熵与信息论',cn:'Entropy & Information Theory',aliases:['熵&信息论','信息论'],pages:[62],plain:'信息论研究信息怎样度量、传输和压缩；熵可以粗略理解为不确定性的大小。',example:'抛一枚公平硬币结果更难猜，信息熵高于一枚几乎总是正面的硬币。',note:'这里的熵是数学量，不完全等同于日常所说的“混乱”。'},
  {term:'马尔可夫过程',cn:'Markov Process',aliases:['马尔可夫过程'],pages:[62],plain:'一种描述状态随时间变化的模型，常假设下一状态主要由当前状态决定。',example:'天气模型只根据今天是晴天还是雨天估计明天的天气。',note:'“只看当前”是常见简化假设，真实任务有时还需要更长历史。'},
  {term:'知识图谱',cn:'Knowledge Graph',aliases:['知识图谱'],pages:[62],plain:'用“实体—关系—实体”的网络组织知识，方便查询和推理。',example:'“上海—位于—中国”“华东师大—位于—上海”可以连接成图。',note:'它描述的是结构化关系，不只是普通图片或统计图。'},
  {term:'预训练',cn:'Pre-training',aliases:['预训练'],pages:[62,63,64,66],plain:'先在大量通用数据上学习基础能力，再把模型用于具体任务。',example:'模型先阅读海量文字，再学习回答遥感问题。',note:'预训练提供通用起点；微调让模型适应具体任务。'},
  {term:'大语言模型（LLM）',cn:'Large Language Model',aliases:['LLM','大语言模型','Vicuna7b'],pages:[62,63,66,70],plain:'在大量文本上训练、包含很多参数、能够理解和生成语言的模型。',example:'根据问题生成解释、摘要或代码。',note:'LLM 的主要输入输出是语言；能同时处理图像等信息时通常称大型多模态模型。'},
  {term:'多模态',cn:'Multimodal',aliases:['多模态','Multimodal'],pages:[1,63,66,70],plain:'同时涉及文字、图像、声音、地图坐标等多种信息形式。',example:'给模型一张卫星图和一个文字问题，让它结合两者回答。',note:'“多”指信息类型，不是简单地把多个文件放在一起。'},
  {term:'大型多模态模型（LMM）',cn:'Large Multimodal Model',aliases:['LMM','大型多模态模型','LMM-based VLMs'],pages:[63,66,70],plain:'把语言模型与视觉等模块连接起来，能够综合处理多种信息的大模型。',example:'查看无人机图片后，用文字回答车辆在哪里、是什么颜色。',note:'VLM 强调视觉与语言；LMM 的模态范围可以更广。'},
  {term:'视觉语言模型（VLM）',cn:'Vision-Language Model',aliases:['VLM','视觉语言'],pages:[63,64,65,66,84,86],plain:'把图像和文字放到同一个任务中学习的模型，可做图文检索、描述、问答和定位。',example:'输入卫星图和“找到机场跑道”，模型输出相应区域。',note:'不同 VLM 的输出差异很大，看到名称后还要看具体任务。'},
  {term:'CLIP',cn:'图文对比预训练模型',aliases:['CLIP','RemoteCLIP','CLIP-RSICD'],pages:[63,64,66],plain:'同时学习图片和文字的表示，使内容匹配的图文在数学空间中更接近。',example:'搜索“河上的桥”，系统把与这句话最接近的图片排在前面。',note:'CLIP 擅长匹配和检索，本身通常不负责生成长篇文字。'},
  {term:'对比学习',cn:'Contrastive Learning',aliases:['CLIP 范式','图文对齐'],pages:[64],plain:'让相关样本的表示靠近、不相关样本的表示远离的一种学习方法。',example:'同一地点的照片与描述拉近，随机地点的图文推远。',note:'“对比”发生在模型表示之间，不只是肉眼比较两张图。'},
  {term:'嵌入 / 表示',cn:'Embedding / Representation',aliases:['表示空间','跨模态表示','嵌入'],pages:[63,64,99,100,101,102,103],plain:'模型把文字、图片或状态转换成一串数字，用这些数字保存对任务有用的信息。',example:'两张都包含机场的图片，其数字表示可能比机场与森林的表示更接近。',note:'嵌入不是原始图片，而是模型提炼出的数字化特征。'},
  {term:'视觉编码器',cn:'Visual Encoder',aliases:['视觉编码器','CLIP-ViT'],pages:[64,66],plain:'把输入图像压缩成模型能够处理的数字特征的模块。',example:'把 504×504 的遥感图变成一组表示道路、建筑和地物关系的向量。',note:'编码器负责“读图”，后面的语言模型或任务头负责生成答案。'},
  {term:'适配器（Adaptor）',cn:'Adapter',aliases:['MLP adaptor','适配器'],pages:[66],plain:'连接两个模型模块的小型网络，用来把一边的输出转换成另一边能理解的形式。',example:'把视觉编码器产生的图像特征转换成语言模型可接收的表示。',note:'适配器像转换插头，但转换的是数字特征。'},
  {term:'MLP',cn:'多层感知机',aliases:['MLP'],pages:[66],plain:'由若干全连接层组成的基础神经网络，常用于转换或组合特征。',example:'把视觉特征从一个维度映射到语言模型需要的维度。',note:'名称含“感知机”，但现代 MLP 通常有多层和非线性函数。'},
  {term:'扩散模型',cn:'Diffusion Model',aliases:['Diffusion','扩散模型'],pages:[63,65],plain:'训练时学习怎样逐步去除噪声；生成时从近似随机噪声开始，一步步形成图像。',example:'根据“洪水后的城市卫星图”这一文字条件生成相应图像。',note:'这里的“扩散”是数学过程，不是图片在空间中真的散开。'},
  {term:'微调',cn:'Fine-tuning',aliases:['微调'],pages:[66],plain:'在已经预训练好的模型上，用较小的专门数据继续训练，使其适应新任务。',example:'把通用图文模型用遥感问答数据继续训练。',note:'微调不是从零训练，通常需要的数据和算力更少。'},
  {term:'LoRA',cn:'低秩适配',aliases:['LoRA'],pages:[66],plain:'微调大模型时，只训练少量新增的小矩阵，而不改动全部参数，从而节省显存和时间。',example:'像在厚教材旁加一套可替换的薄笔记，而不是重写整本教材。',note:'LoRA 是高效微调方法，不是一个独立的大模型。'},
  {term:'冻结权重',cn:'Frozen Weights',aliases:['固定 MLP','固定','冻结'],pages:[66],plain:'训练时保持某些模型参数不变，只更新选定部分。',example:'保留视觉编码器原有看图能力，只训练语言侧的 LoRA 参数。',note:'冻结可以省算力，但也限制了该模块适应新数据的程度。'},
  {term:'遥感',cn:'Remote Sensing',aliases:['遥感','Remote'],pages:[1,64,65,66,68,70,71,84],plain:'不直接接触目标，而是利用卫星、飞机或无人机传感器远距离获取地表信息。',example:'卫星拍摄农田影像，用来观察作物长势。',note:'遥感图不只是普通照片，还常包含位置、时间、波段和分辨率信息。'},
  {term:'光学遥感影像',cn:'Optical Remote-sensing Image',aliases:['光学遥感图像'],pages:[64],plain:'传感器记录可见光或邻近波段形成的地表图像，外观较接近日常照片。',example:'Sentinel-2 拍摄的城市、森林和水体影像。',note:'云会遮挡光学影像；雷达遥感则能使用不同的成像原理。'},
  {term:'空间分辨率',cn:'Spatial Resolution',aliases:['分辨率'],pages:[64,66],plain:'一个像素在地面上代表多大范围。数值越小，通常能看见越细的目标。',example:'1 米分辨率表示一个像素大约对应地面 1×1 米。',note:'图片像素数量高，不一定等于地面空间分辨率高。'},
  {term:'重访周期',cn:'Revisit Time',aliases:['重访'],pages:[64],plain:'卫星再次观测同一地点需要的时间，反映更新频率。',example:'5 天重访意味着理想情况下约每 5 天可获得一次同一区域的新观测。',note:'实际可用影像还会受云层、轨道和传感器状态影响。'},
  {term:'地理标记',cn:'Geotag',aliases:['地理位置','精确到街道'],pages:[64],plain:'随照片保存的经纬度或地点信息，使图片能与地图位置对应。',example:'手机照片记录拍摄地点，可用于匹配附近的卫星影像。',note:'公开使用地理标记时应注意隐私和坐标误差。'},
  {term:'Google Earth Engine',cn:'云端地学计算平台',aliases:['Google Earth Engine'],pages:[64],plain:'在线访问和处理大量卫星影像与地理数据的平台，省去逐景下载和本地存储的工作。',example:'按坐标和日期批量筛选 Sentinel-2 影像。',note:'它是数据与计算平台，不等同于 Google Earth 桌面地球浏览器。'},
  {term:'NAIP',cn:'美国国家农业影像计划',aliases:['NAIP'],pages:[64],plain:'美国定期获取的高分辨率航空影像数据，常用于土地、农业和地物研究。',example:'将地面街景照片与同一地点的 NAIP 航空图配对。',note:'主要覆盖美国，不是全球卫星数据集。'},
  {term:'Sentinel-2',cn:'哨兵二号卫星',aliases:['Sentinel-2'],pages:[64],plain:'欧洲哥白尼计划的多光谱地球观测卫星，提供全球陆地影像。',example:'用不同时间的 Sentinel-2 影像观察植被或城市变化。',note:'它有多个光谱波段，信息比普通 RGB 照片更丰富。'},
  {term:'数据集',cn:'Dataset',aliases:['数据集','Dataset'],pages:[64,66,72,73,74,75,76,77,78,80,89,90,91],plain:'按明确规则收集并组织的一批样本，通常包含输入、标签和数据划分。',example:'一组遥感图片，每张图片配有文字描述和目标框。',note:'数据量大不等于质量高；还要看标注、覆盖范围和偏差。'},
  {term:'标签 / 标注',cn:'Label / Annotation',aliases:['标注','标签'],pages:[64,66,89,90,91],plain:'训练或评价时附在样本上的正确答案或说明。',example:'在图片上画框并写“汽车”，就是一种标注。',note:'标签可能有错误或歧义，因此需要质量检查。'},
  {term:'训练集与测试集',cn:'Train Set & Test Set',aliases:['训练集','测试集','测试基准'],pages:[64,66],plain:'训练集用来让模型学习；测试集留到最后衡量模型面对未见数据的能力。',example:'用 80% 图片训练，保留 20% 图片测试。',note:'如果测试图片泄漏进训练过程，结果会虚高。'},
  {term:'基准（Benchmark）',cn:'统一评测基准',aliases:['Benchmark','基准'],pages:[64,86,89],plain:'由任务、数据和评价指标组成的统一考试，用来公平比较不同方法。',example:'所有模型在同一批图片上定位目标，再比较准确率。',note:'Benchmark 不是单指一个数据文件，而是一整套评测规则。'},
  {term:'场景分类',cn:'Scene Classification',aliases:['Scene classification','Scene Classification','RSSC'],pages:[64,66],plain:'判断整幅图像主要属于哪种场景。',example:'把遥感图分成机场、港口、居民区或森林。',note:'场景分类判断整图；目标检测还要指出对象的位置。'},
  {term:'图像分割',cn:'Segmentation',aliases:['Segmentation','分割'],pages:[64,77,78],plain:'为图像中的每个像素判断类别或所属对象，得到精细区域。',example:'把卫星图中所有水体像素涂成同一种颜色。',note:'分割比矩形框定位更精细，但标注成本也更高。'},
  {term:'检索',cn:'Retrieval',aliases:['Retrieval','检索'],pages:[64,84],plain:'从大量数据中找出与查询最相关的内容。',example:'输入“红色轿车”，从无人机影像库中找出对应车辆。',note:'检索通常返回排序结果，不等于生成一张新图片。'},
  {term:'图像描述（Caption）',cn:'Image Captioning',aliases:['Caption','Cap.','图像描述'],pages:[67,71,72,73,79,89],plain:'让模型用自然语言说明整张图或指定区域里有什么、发生了什么。',example:'“一座桥横跨河流，桥上有三辆汽车。”',note:'描述回答开放问题；分类通常只从固定类别中选答案。'},
  {term:'区域描述',cn:'Region Caption',aliases:['Region Cap.','Region Caption','Region Captioning'],pages:[66,72],plain:'只描述图像中某个指定局部区域，而不是整幅图。',example:'给出一个框，模型描述“框内是一辆停在路边的白色卡车”。',note:'输入中必须说明关注哪个区域。'},
  {term:'细节描述',cn:'Detailed Caption',aliases:['Detailed Cap.'],pages:[73],plain:'比普通图像描述包含更多对象、属性、数量和关系的信息。',example:'不仅说“有车辆”，还说明车辆数量、颜色、方向和周围道路。',note:'文字更长不一定更准确，细节也需要图像证据。'},
  {term:'时序描述',cn:'Temporal Caption',aliases:['Temporal Cap.'],pages:[73],plain:'结合不同时间拍摄的影像，描述场景发生了什么变化。',example:'“一年后，该地块由裸地变成了建筑工地。”',note:'需要区分真实变化与季节、光照或成像差异。'},
  {term:'视觉问答（VQA）',cn:'Visual Question Answering',aliases:['VQA','Visual Question Answering','RSVQA'],pages:[64,66,67,71,74,75,79],plain:'输入图像和自然语言问题，让模型根据图像内容回答。',example:'问题“图中有几架飞机？”，模型回答“4 架”。',note:'答案正确也可能来自数据偏差，因此要检查模型是否真正利用图像。'},
  {term:'区域视觉问答',cn:'Region VQA',aliases:['Region VQA'],pages:[74],plain:'问题只针对图像中指定区域，要求模型关注局部而非整图。',example:'框出停车场后问“这个区域中有多少辆车？”',note:'区域选择错了，后续回答即使语言流畅也没有意义。'},
  {term:'时序视觉问答',cn:'Temporal VQA',aliases:['Temporal VQA'],pages:[75],plain:'根据多个时间点的影像回答关于变化的问题。',example:'“两期影像之间新增了几栋建筑？”',note:'模型需要同时理解空间位置和时间对应。'},
  {term:'视觉定位（Grounding）',cn:'Visual Grounding',aliases:['Visual Grounding','Grounding','视觉定位'],pages:[66,67,71,75,76,77,78,79,86,88],plain:'把一句语言描述与图像中的具体对象或区域对应起来。',example:'读到“桥旁的红色汽车”，在图中画框指出它。',note:'地理定位回答“这张图在地球哪里”；视觉定位回答“描述的对象在图中哪里”。'},
  {term:'有根据的描述 / 问答',cn:'Grounded Caption / VQA',aliases:['Grounded Cap.','Grounded VQA'],pages:[73,75],plain:'模型除了生成文字，还要指出支持文字答案的图像区域，让结论可以追溯到视觉证据。',example:'回答“有两架飞机”时，同时框出这两架飞机。',note:'Grounded 强调答案与证据绑定，不只是答案看起来合理。'},
  {term:'指代表达',cn:'Referring Expression',aliases:['Referring Expression','指代表达'],pages:[66,76,77,78],plain:'用语言从多个对象中唯一指出某一个目标的表达。',example:'“道路左侧、靠近蓝色屋顶的第二辆白车”。',note:'“汽车”通常不够明确；指代表达需要包含可区分条件。'},
  {term:'REC',cn:'指代表达理解',aliases:['REC','Generalized REC'],pages:[76],plain:'根据指代表达在图中找出目标，通常输出一个矩形边界框。',example:'输入“最靠近路口的卡车”，输出包住该卡车的方框。',note:'REC 输出框；RES 输出更精细的像素区域。'},
  {term:'RES',cn:'指代表达分割',aliases:['RES','Generalized RES'],pages:[77,78],plain:'根据指代表达找出目标，并输出目标每个像素构成的掩膜。',example:'把“河中央的小岛”完整轮廓涂出来。',note:'掩膜比边界框更精确，制作和评价也更复杂。'},
  {term:'边界框',cn:'Bounding Box',aliases:['边界框','目标框'],pages:[76,84,86],plain:'用矩形框粗略标出目标在图像中的位置。',example:'用左上角和右下角坐标框住一辆汽车。',note:'框内会包含部分背景，不能表示目标的精确轮廓。'},
  {term:'掩膜',cn:'Mask',aliases:['掩膜','像素级'],pages:[77,78],plain:'与原图大小对应的像素地图，用来标记哪些像素属于目标。',example:'目标像素记为 1，背景像素记为 0。',note:'它常用于分割任务，不是遮住图片的普通贴纸。'},
  {term:'广义任务',cn:'Generalized Setting',aliases:['Generalized'],pages:[76,78],plain:'把任务从较理想、类别固定的条件扩展到更多对象、未知类别或更复杂场景。',example:'模型不仅找训练时见过的车辆，还要处理新类别和没有目标的情况。',note:'不同论文对 Generalized 的具体定义可能不同，应查看其任务说明。'},
  {term:'时序视觉定位（T-GREC / T-GRES）',cn:'Temporal Grounding',aliases:['T-GREC','T-GRES'],pages:[77,78],plain:'结合多个时间点的图像和文字描述，定位发生变化或满足时序条件的目标。',example:'找出“最近新建的建筑”，需要比较前后两期影像。',note:'既要对齐不同时间的图像，又要完成定位或分割。'},
  {term:'地理定位',cn:'Geo-Localization',aliases:['Geo-Localization','地理定位'],pages:[68],plain:'根据照片或遥感图的视觉线索，判断它在真实地球上的位置。',example:'把一张街景与大范围卫星地图匹配，估计拍摄经纬度。',note:'它与 GPS 定位不同，可以只依赖图像内容完成估计。'},
  {term:'商业航天',cn:'Commercial Spaceflight',aliases:['商业航天'],pages:[70],plain:'由市场化企业参与卫星、火箭、发射和数据服务等航天活动。',example:'公司建设遥感卫星星座并向用户提供影像服务。',note:'它不仅指太空旅游，也包括卫星制造、发射和数据应用。'},
  {term:'低空经济',cn:'Low-altitude Economy',aliases:['低空经济'],pages:[70],plain:'围绕低空飞行器及其运营形成的产业活动，包括无人机物流、巡检、测绘和载人飞行等。',example:'无人机为电网巡检或在园区配送物品。',note:'发展低空应用还涉及空域、安全、通信和法规。'},
  {term:'卫星互联网',cn:'Satellite Internet',aliases:['卫星互联网'],pages:[70],plain:'通过通信卫星为地面、海上或空中用户提供网络连接。',example:'偏远地区使用低轨卫星终端接入互联网。',note:'它主要解决通信连接，与拍摄地球的遥感卫星任务不同。'},
  {term:'智能解译',cn:'Intelligent Interpretation',aliases:['智能解译','解译技术'],pages:[70,84],plain:'用算法从遥感影像中自动提取有意义的信息。',example:'自动识别建筑、道路、船只并统计变化。',note:'“解译”不仅是看图，还要把像素转换成可使用的地理信息。'},
  {term:'智能体（Agent）',cn:'AI Agent',aliases:['智能体','Agent'],pages:[84],plain:'能感知环境、依据目标作出计划并采取行动的系统。',example:'无人机智能体观察场景、决定去哪里拍摄，再根据新图像调整路线。',note:'智能体强调持续的“感知—决策—行动”过程，不只是一次回答。'},
  {term:'空间智能',cn:'Spatial Intelligence',aliases:['空间智能','空间理解'],pages:[1,69,84],plain:'理解对象在哪里、大小和方向如何、彼此有什么关系，并利用这些信息完成推理或行动的能力。',example:'判断车辆在桥的哪一侧、离无人机多远，并规划接近路线。',note:'识别对象类别只是空间智能的一小部分。'},
  {term:'空间感知',cn:'Spatial Perception',aliases:['空间感知'],pages:[84,85],plain:'从传感器数据中估计物体的位置、距离、方向、尺寸和空间关系。',example:'由无人机影像估计一辆车的三维坐标和长宽高。',note:'二维检测给出图中位置；空间感知还关心真实世界几何。'},
  {term:'三维定位',cn:'3D Localization',aliases:['3D定位','三维位置'],pages:[84,95],plain:'估计目标在三维空间中的位置，通常需要 x、y、z 坐标或等价的几何信息。',example:'确定车辆在地图中的平面坐标以及相对地面的高度。',note:'单张二维图会丢失深度，常需相机参数、多视角或其他传感器。'},
  {term:'细粒度识别',cn:'Fine-grained Recognition',aliases:['Fine-Grained','细粒度'],pages:[84,85],plain:'在很相似的大类别内部继续区分更具体的子类。',example:'不只识别“汽车”，还要区分具体品牌和车型。',note:'差异往往很小，因此需要更清晰的外观或尺寸信息。'},
  {term:'零样本',cn:'Zero-shot',aliases:['Zero-Shot','零样本'],pages:[85,99],plain:'模型在没有看过目标任务的专门训练样本时，直接利用已有知识完成任务。',example:'没有用某款新车型训练，模型仍根据文字和图像特征尝试识别。',note:'零样本不等于模型从未训练过，而是没有针对当前类别或任务再训练。'},
  {term:'隐式指令',cn:'Implicit Instruction',aliases:['隐式','Implicit'],pages:[86,87,88],plain:'没有直接说出目标名称，而是通过目的、情境或条件让系统推断要找什么。',example:'“找到最需要救援的车辆”没有直接给出颜色和位置。',note:'系统必须先把需求转成可观察条件，再进行视觉定位。'},
  {term:'思维链',cn:'Chain of Thought',aliases:['思维链','隐转显'],pages:[88],plain:'把复杂问题拆成若干中间推理步骤，再得到最终答案的方法。',example:'先判断“需要救援”的视觉迹象，再筛选车辆，最后定位目标。',note:'写出步骤可以帮助检查错误，但文字步骤不一定完全等于模型内部机制。'},
  {term:'人工 / 自动 / 半自动构造',cn:'Dataset Construction Modes',aliases:['完全人工构造','完全自动构造','半自动构造'],pages:[89,90,91],plain:'描述数据由谁生成和检查：全部由人完成、全部由程序完成，或模型生成后由人审核。',example:'先让模型写描述，再由标注员纠错，属于半自动构造。',note:'自动化程度越高不代表质量必然越高，仍要验证规则和样本。'},
  {term:'交叉验证（人工）',cn:'Cross-checking',aliases:['验证（交叉）','交叉'],pages:[89],plain:'让不同人员相互检查标注，减少单个标注者的疏漏和主观偏差。',example:'甲完成车辆框，乙独立复核并记录分歧。',note:'这里指人工交叉检查，不一定是机器学习中的 k 折交叉验证。'},
  {term:'抽样检查',cn:'Sampling Inspection',aliases:['抽样'],pages:[91],plain:'不检查全部数据，而是按规则选取一部分样本评估整体质量。',example:'随机检查每批数据的 5%，并额外检查模型最不确定的样本。',note:'抽样方案不合理会漏掉系统性错误。'},
  {term:'CVPR / ICLR / NeurIPS',cn:'人工智能学术会议',aliases:['CVPR','ICLR','NeurIPS'],pages:[64,66,89,90,91],plain:'研究人员发表和交流最新成果的重要国际会议。CVPR 偏计算机视觉，ICLR 偏学习表示，NeurIPS 涵盖机器学习与相关领域。',example:'课件用会议和年份说明案例论文的发表来源。',note:'会议名称说明发表场合，不直接保证某个方法适合所有任务。'},
  {term:'Oral',cn:'会议口头报告',aliases:['Oral'],pages:[89],plain:'会议从录用论文中选出一部分进行现场或线上口头报告，通常表示该工作受到较高关注。',example:'“CVPR 2025 Oral”表示论文被录用并获口头报告展示。',note:'Oral 是展示形式，不是新的算法类型。'},
  {term:'IEEE TGRS / ISPRS JPRS',cn:'遥感领域学术期刊',aliases:['IEEE Transactions on Geoscience and Remote Sensing','ISPRS Journal of Photogrammetry and Remote Sensing','IEEE TGRS','ISPRS JPRS'],pages:[84,85,86,88],plain:'发表遥感、摄影测量、地理空间信息等研究成果的国际学术期刊。',example:'课件中的 AirSpatialBot 和 DVGBench 分别标注了论文发表期刊。',note:'期刊名称用于追溯论文来源，不是模型名称。'},
  {term:'中科院一区',cn:'期刊分区标签',aliases:['中科院一区'],pages:[84,85,86,88],plain:'中国科学院文献情报中心期刊分区中的一个等级，用于从学科角度参考期刊影响力。',example:'课件用“一区”辅助说明案例期刊在相关学科中的位置。',note:'分区会随年份变化，也不能替代对单篇论文质量的判断。'},
  {term:'无人机（UAV）',cn:'Unmanned Aerial Vehicle',aliases:['无人机','UAV','Drones','Quadrotors'],pages:[84,86,93,94,95,96,97,98,99],plain:'不载驾驶员、通过遥控或自主系统飞行的航空器。四旋翼是常见无人机结构。',example:'无人机携带相机巡检桥梁或采集灾区影像。',note:'“无人”不等于完全自主，许多无人机仍由人控制或监督。'},
  {term:'自主飞行',cn:'Autonomous Flight',aliases:['自主飞行','Autonomous'],pages:[93,94,95],plain:'飞行器根据传感器和算法自行完成定位、规划、避障和控制，而不是由人逐步操纵。',example:'给定扫描目标后，无人机自己规划路线并保持稳定。',note:'自主程度有高低，真实任务通常仍需安全边界和人工监督。'},
  {term:'主动感知',cn:'Active Perception',aliases:['主动感知'],pages:[95,96],plain:'系统主动选择下一步动作或观察位置，以获得更有用的信息。',example:'发现建筑被树遮挡后，无人机绕到另一侧补拍。',note:'普通识别处理已有图像；主动感知把“去哪里看”也纳入任务。'},
  {term:'基础模型',cn:'Foundation Model',aliases:['Foundation Model'],pages:[95],plain:'在大规模通用数据上训练、可适配多种下游任务的模型。',example:'同一视觉基础模型经少量调整后用于检测、分割或路径选择。',note:'“基础”指通用底座，不表示它无需验证就能直接用于真实系统。'},
  {term:'三维结构扫描',cn:'3D Structure Scanning',aliases:['3D Structure Scanning','三维结构扫描'],pages:[95],plain:'从多个视角采集数据，重建物体或环境的三维形状。',example:'无人机绕建筑飞行，拍摄多角度照片并生成三维模型。',note:'只拍一张正面照片通常无法完整恢复被遮挡的背面。'},
  {term:'开放世界',cn:'Open-world Environment',aliases:['Open-World','开放世界'],pages:[95],plain:'系统可能遇到训练时没有见过的对象、场景或条件，不能假设所有类别都预先已知。',example:'无人机在陌生山区扫描从未出现过的建筑结构。',note:'开放世界比固定测试集更接近真实环境，也更难保证可靠性。'},
  {term:'具身智能',cn:'Embodied Intelligence',aliases:['具身','物理世界'],pages:[92,93,94,95,96,97,98,99,100,101,102,103],plain:'智能系统通过身体或机器人在环境中感知和行动，并从反馈中持续调整。',example:'无人机听懂指令、找到目标、飞过去并完成抓取。',note:'它强调闭环行动，和只在屏幕中回答问题的模型不同。'},
  {term:'抓取与交互',cn:'Grasping & Interaction',aliases:['抓取','grasping','interaction'],pages:[98],plain:'机器人利用机械结构接触、拿取或操作真实物体。',example:'飞行机器人稳定靠近物体，用爪子抓住并搬运。',note:'除了识别目标，还需考虑力、姿态、碰撞和飞行稳定。'},
  {term:'状态估计',cn:'State Estimation',aliases:['状态估计'],pages:[93,94,95,96,97,98,99],plain:'根据相机、惯性测量等传感器，估计飞行器和环境当前处于什么状态。',example:'估计无人机的位置、速度和朝向。',note:'传感器有噪声，因此估计值不是绝对准确的真值。'},
  {term:'规划',cn:'Planning',aliases:['路径规划','路径选择'],pages:[93,94,95,96,97,98,99],plain:'根据目标和约束决定接下来采取哪些动作。',example:'在避开建筑的同时选择最短航线到达目标。',note:'规划决定“怎么走”，控制负责把计划转成连续执行信号。'},
  {term:'控制',cn:'Control',aliases:['Control','控制策略','控制'],pages:[93,94,95,96,97,98,99,100,101,102,103],plain:'根据目标状态和实际反馈不断调整电机或执行器，使系统按计划运动。',example:'无人机偏离航线时自动改变四个电机转速拉回。',note:'控制需要快速反馈，并受真实物理规律约束。'},
  {term:'动力学',cn:'Dynamics',aliases:['动力学'],pages:[93,94,95,96,97,98,99],plain:'研究力和运动之间关系的模型，说明动作会怎样改变速度、姿态和位置。',example:'增加某一侧电机推力会使四旋翼倾斜并横向移动。',note:'图像模型只负责看懂画面时，通常不需要完整处理动力学。'},
  {term:'反馈闭环',cn:'Feedback Loop',aliases:['反馈','闭环'],pages:[93,94,95,96,97,98,99],plain:'执行动作后再次测量结果，把误差送回系统继续调整，形成循环。',example:'无人机飞近目标后重新测距，再修正速度和方向。',note:'没有反馈的开环动作难以应对风、误差和环境变化。'},
  {term:'世界模型',cn:'World Model',aliases:['World Models','世界模型'],pages:[99,100,101,102,103],plain:'让系统在内部表示环境状态，并预测采取某个动作后可能发生什么。',example:'无人机在真正转弯前，先预测转弯后的视野和位置。',note:'它不一定重建每个像素，关键是保留规划和控制需要的信息。'},
  {term:'JEPA',cn:'联合嵌入预测架构',aliases:['JEPA','SkyJEPA'],pages:[99,100,101,102,103],plain:'在抽象表示空间中预测缺失或未来信息，而不是必须逐像素生成画面。',example:'根据当前飞行状态的表示，预测几秒后的状态表示。',note:'预测表示通常更关注结构和语义，可减少对无关像素细节的建模。'},
  {term:'长时程',cn:'Long-horizon',aliases:['Long-Horizon','长时程'],pages:[99,100,101,102,103],plain:'任务需要考虑较长的一串未来步骤，而不是只预测下一瞬间。',example:'规划无人机接下来几十个动作完成穿越和着陆。',note:'预测时间越长，微小误差越容易累积。'},
  {term:'仿真到现实（Sim-to-Real）',cn:'Simulation to Reality',aliases:['Sim-to-Real','仿真到现实'],pages:[99,100,101,102,103],plain:'先在计算机模拟环境中训练或测试，再把能力迁移到真实设备。',example:'在模拟器中训练无人机避障，然后部署到真实四旋翼。',note:'仿真与现实存在外观和物理差异，迁移时要处理这种差距。'},
  {term:'网页爬虫',cn:'Web Crawler',aliases:['爬虫','Crawl video','Crawl4AI','Crawl'],pages:[14,24,25,26,27],plain:'自动访问网页并提取所需信息的程序。',example:'批量读取视频标题、播放量和链接，保存成表格。',note:'爬虫应遵守网站条款、访问频率限制和数据使用规范。'},
  {term:'结构化数据',cn:'Structured Data',aliases:['结构化','CSV','字段'],pages:[14,15,16,17,18,24,25,26,27],plain:'按固定字段和格式组织的数据，便于程序读取、筛选和统计。',example:'每行一个视频，每列分别是标题、播放量和发布时间。',note:'网页文字被抓下来不等于已经结构化，还需确定字段。'},
  {term:'XPath / CSS 选择器',cn:'网页元素定位规则',aliases:['XPath','CSS选择器'],pages:[27],plain:'用页面结构或样式规则指出要提取哪个网页元素。',example:'定位文章标题所在的 HTML 标签。',note:'网页结构改变后，旧选择器可能失效。这里的 CSS 选择器不是单纯的美化样式。'},
  {term:'反爬机制',cn:'Anti-scraping',aliases:['反爬'],pages:[27],plain:'网站用于限制异常自动访问、保护服务和数据的技术措施。',example:'频繁请求时要求验证码或暂时限制访问。',note:'技术上能够获取不代表允许使用，应遵守规则和授权范围。'},
  {term:'仓库',cn:'Repository',aliases:['仓库','repository'],pages:[28,29,30,31,32,33,34,35,36,37,40,41,42,43,44,45,46],plain:'集中保存项目文件和修改历史的空间，GitHub 上的一个项目通常对应一个仓库。',example:'学术主页的 HTML、图片和配置文件放在同一个仓库。',note:'仓库类似带版本历史的项目文件夹，不只是网盘目录。'},
  {term:'Fork',cn:'派生仓库',aliases:['Folk','Fork'],pages:[32,33,34],plain:'在自己的 GitHub 账户下复制一个可独立修改的仓库，同时保留与原项目的来源关系。',example:'Fork 主页模板后，修改成自己的学术主页。',note:'课件中的 “Folk” 应理解为 GitHub 的 “Fork”；它不同于只下载压缩包。'},
  {term:'GitHub Pages',cn:'静态网站托管服务',aliases:['github pages','GitHub Pages'],pages:[35,36,37,38,39],plain:'GitHub 把仓库里的网页文件构建并发布为公开网站的服务。',example:'把个人主页仓库发布成 username.github.io。',note:'仓库内容更新后，网页通常还要等待一次构建和部署。'},
  {term:'构建与部署',cn:'Build & Deploy',aliases:['build github pages','网站部署'],pages:[35,36,37,38,39],plain:'构建是把源文件转换成可访问网站；部署是把生成结果发布到服务器。',example:'修改配置后，GitHub Pages 自动重新生成并上线页面。',note:'文件已经提交不代表网页立刻更新，部署需要时间。'},
  {term:'YAML 配置文件',cn:'_config.yml',aliases:['_config.yml','config.yml','YAML'],pages:[41,42,43,44],plain:'用缩进和“键: 值”保存网站设置的文本文件。',example:'设置网站标题、作者、邮箱或主题。',note:'缩进和符号很重要；它保存配置，不是普通文章正文。'},
  {term:'Markdown',cn:'.md 轻量标记文本',aliases:['about.md','.md'],pages:[45,46],plain:'用少量符号表示标题、列表和链接的纯文本格式，常用于写网页内容和项目说明。',example:'“# 标题”表示一级标题，“[文字](链接)”表示超链接。',note:'Markdown 文件通常会被网站系统转换成 HTML。'},
  {term:'PR',cn:'Pull Request',aliases:['PR'],pages:[21],plain:'向一个代码仓库提出合并修改的请求，便于他人查看差异、讨论和审核。',example:'完成主页修改后提交 PR，请维护者合并。',note:'PR 不是直接等于发布；它首先是一次可审查的修改提议。'},
  {term:'模型架构',cn:'Model Architecture',aliases:['模型架构','网络结构','architecture'],pages:[63,64,65,66],plain:'规定模型由哪些模块组成、信息怎样在模块之间流动的总体设计。',example:'视觉编码器先读图，适配器转换特征，语言模型再生成答案。',note:'架构像建筑蓝图；模型参数则是训练后填入蓝图中的具体数值。'},
  {term:'训练策略',cn:'Training Strategy',aliases:['训练策略'],pages:[64,66],plain:'训练模型时关于数据、参数更新、学习阶段和资源使用的一整套安排。',example:'先冻结视觉编码器，只用 LoRA 微调语言模型。',note:'它说明“怎样训练”，不等于模型的网络结构。'},
  {term:'GPU / A100',cn:'图形处理器 / AI 加速卡',aliases:['A100','GPU','硬件条件'],pages:[64,66],plain:'GPU 能并行完成大量数值计算；A100 是一款常用于训练深度学习模型的数据中心 GPU。',example:'“4 块 A100（40G）”说明实验使用了四张卡，每张约有 40GB 显存。',note:'GPU 显存影响可处理的模型和数据规模；它与电脑硬盘容量不同。'},
  {term:'跨视角数据',cn:'Cross-view Data',aliases:['地面-卫星图像对','地面上拍摄','对应的遥感图片'],pages:[64],plain:'同一地点由不同平台、不同高度或不同方向拍摄的数据。',example:'把街道照片与该地点上空的卫星图配成一对。',note:'视角差异很大，同一建筑在两张图中的外观可能完全不同。'},
  {term:'模板填充',cn:'Template Filling',aliases:['Template filling'],pages:[19,20],plain:'把结构固定的内容模板留出若干空位，再用数据自动替换这些空位。',example:'把视频标题、链接和简介自动填进统一的发布格式。',note:'模板提高一致性，但生成结果仍需人工检查。'},
  {term:'评分与排序',cn:'Scoring & Ranking',aliases:['Compute scores','scores'],pages:[16,17,18],plain:'把多个判断条件转换成分数，再按分数排列候选结果。',example:'综合播放量、点赞率和发布时间，给视频选题排序。',note:'排序结果取决于指标和权重；高分不等于绝对更好。'},
  {term:'顶会投稿',cn:'Top-conference Submission',aliases:['顶会投稿','顶会'],pages:[81],plain:'研究者把论文提交到本领域影响力较大的学术会议，由同行评审决定是否录用。',example:'CVPR、ICLR 和 NeurIPS 每年会收到大量论文投稿。',note:'投稿数量反映研究活跃度，但不等于所有投稿都被录用。'},
  {term:'模型规模 / 参数量',cn:'Model Size / Parameter Count',aliases:['大模型','小模型','模型参数'],pages:[55,62,70,82,83],plain:'参数是模型在训练中学到的数值；参数数量常用来粗略表示模型规模。',example:'数十亿参数的模型通常比数百万参数模型需要更多显存和计算。',note:'规模更大不保证任务效果更好，还要看数据、架构和训练方式。'}
];
